### ISSUE TITLE
modal window does not work

### ISSUE THREAD

**Issue by inmoel** [fancyapps/fancyBox#1145]
Hi Fancybox,
 
My company uses Zendesk for our support, almost ½ year ago, I installed the fancybox package to our help center, and it worked.
Since our product now has another layout, we need to change all the images.
But when I insert the new image, and attach the asset + class=”fancybox”
<a class="fancybox" href="//p3.zdassets.com/hc/theme_assets/942455/200152235/valgmuligheder.png"><img src="/hc/da/article_attachments/204769025/valgmuligheder.png" alt="" width="700" height="214" /></a>
 
The image does not open in a modal window, but as the only picture in another tab (it opens the asset-link).

I thought it was something in the CSS or JS, but I re-copy-pasted the coding, as suggested on the help site.
 
**How can I get to open my images in a modal window?**
 
My example is the first image in this article: http://support.gratisal.com/hc/da/articles/208468529/
 
I did send my inqury to Zendesk, and they supervised me to ask you, if you knew what to do.
 
Kind regards, 
Ida Nicole Mølgaard

**Comment by fancyapps** [comment]
Have you checked JS console for any JS message?

**Comment by inmoel** [comment]
Hi,
I don't know if there is such thing in Zendesk. Do you know where to specifcally to look for the JS console?
Greetings,
Ida

**Comment by fancyapps** [comment]
You can access developer tools by pressing F12; then select "Console" and look for any clue.

Anyway, there is no much I can help you. If your images have "fancybox" class and you call $(".fancybox").fancybox(); on page load, then it should definitely work. If not, then in 99% cases the problem is caused by:
1) some other script (any JS error can break further execution of JS;
2) JS file is not loaded (wrong path/missing file);
3) sometimes users are not aware that .fancybox(); gets called multiple times (this is typically for WordPress when using many plgugins).
