### ISSUE TITLE
HTML5 <video> and <audio>

### ISSUE THREAD

**Issue by heruan** [fancyapps/fancybox#116]
It would be nice to have new types 'video' and 'audio' to create HTML5 `<video>` and `<audio>` elements.

**Comment by lolametro** [comment]
I'd be very happy about this, too!
Hope this is planned for the near future.

**Comment by fancyapps** [comment]
Hello, everyone!

Sorry, I do not think that there will be included functionality to create `<video>`/`<audio>` elements, because there are so many attributes (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) and creating an option for everyone of them would produce redundant code.

You can just simply create your video/audio element and display as an inline element:

<p>
  <a data-fancybox data-src="#modal" href="javascript:;" class="btn">Open demo</a>
</p>

```HTML
<div id="modal" class="modalVideo">
  <video controls>
    <source
            src="http://ripbang.com/Home06/ShowReel2011.mov"
            type="video/mov">
    <source
            src="http://ripbang.com/Home06/ShowReel2011.mp4"
            type="video/mp4">
    <source
            src="http://ripbang.com/Home06/ShowReel2011.ogv"
            type="video/ogg">
    Your browser doesn't support HTML5 video tag.
  </video>
</div>
```

And recent versions of fancyBox will automatically play/stop it so you do not need to do that manually.

Demo - https://codepen.io/anon/pen/eeLNwQ?editors=1100

**Comment by fancyapps** [comment]
Hello, again!

After recent feedback, it was decided to include basic html5 video support. You can now create links like this:

`<a data-fancybox href="http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4" class="btn">Open demo</a>`

Demo - https://codepen.io/anon/pen/vWzzQz?editors=1000

**Comment by Spica2** [comment]
Hello, nice to have this now.
Only in IE (Edge) the video controlls are inactive. Any fix for that?

**Comment by MarkoD** [comment]
Thanks, that works! Do you have an ETA when will v3.3 be released?

**Comment by fancyapps** [comment]
Honestly, it would be already released if there would be less distracting questions, like when it will be released 😄 But no worry, I`m right now working on the docs and will publish afterwards.
