### ISSUE TITLE
iFrame custom height/width CSS gets clobbered when iframe.preload = true

### ISSUE THREAD

**Issue by Phil-G** [fancyapps/fancyBox#1184]
Is this intentional? When preload = true, height/width is auto calculated which leads to some very strange heights when the content is another web page.

**Comment by fancyapps** [comment]
Well, at some point there were two options: `preload` and something like `autoSize`. But this caused some problems, because:
1) `autoSize` would actually depend on `preload` property - because we, obviously, can`t calculate content dimensions before it is actually finished loading;
2) on the other hand, `preload` would depend on success of loading the content and whether it would be accessible due to browser security policy (you can`t access if there is an error or the page is from other domain name).

And there also was a problem if someone would want to refine dimensions using max/min values (e.g., making it responsive); And so it was decided to simplify everything - just keep one `preload` property and make it possible to resize using CSS. 

But now I was thinking and I got an idea - what if the script would check current options and see if they contain width/height properties like `$('selector').fancybox({ iframe : { css : { width: ..., height: ...}}})` - and then it would use them instead of calculated dimensions.

**Comment by Phil-G** [comment]
Checking for a height/width CSS options override sounds like it will work, otherwise noting the caveat that CSS height/width can't be set if `preload `= true is also acceptable.

**Comment by fancyapps** [comment]
The last commit contains update to this issue - you can now override CSS width/height rules using JS.
