### ISSUE TITLE
ajax on safari opens at bottom of page

### ISSUE THREAD

**Issue by saltnpixels** [fancyapps/fancyBox#1187]
for some strange reason on safari, my ajax page opens but it opens and shows the bottom of the opened page... I have to scroll up to the top....

**Comment by saltnpixels** [comment]
I'm using the callback for now to scroll to top. 

Also if using Ajax to load a selector. Does it still query for the whole page? And then get only the selector. Or does it really only get the selector elemen?

**Comment by fancyapps** [comment]
1) Are you expierencing this issue for your page only? E.g., is Ajax example found on homepage (http://fancyapps.com/fancybox/3/ working ok for you? I`m asking this, because I do no see any issue. Maybe your ajax response contains something that could break the layout?

2) The script loads whole content and then simply filters by selector. Not very efficient, but there are people who are happy about having such option.

**Comment by saltnpixels** [comment]
Your ajax demo is a small page. if its long it opens in safari in the middle of the ajax page.
If you make your window small enough to see the demo need scrolling you will see how it opens.
Here.

![demo-ajax](https://cloud.githubusercontent.com/assets/11615474/22081929/9a64311c-dd93-11e6-9878-3109fe9a283b.gif)

**Comment by fancyapps** [comment]
Ok, I think I figured out what is causing this behavior. You see, by default the script tries to focus on the first focusable element. In this demo, the first one is a link. The browser centers content so that focused element is visible. Try disabling that by setting "focus: false".

**Comment by saltnpixels** [comment]
Seems to have fixed it!
thanks.

Great!

**Comment by saltnpixels** [comment]
I dot want to reopen this issue but on mobile safari it still happens sometimes...

**Comment by fancyapps** [comment]
I will push today another update, maybe it will fix this.
Anyway, It would be great if you could provide a reproducible demo.
