### ISSUE TITLE
Clicked element in v3

### ISSUE THREAD

**Issue by h4mpy** [fancyapps/fancyBox#1193]
How to get clicked element attributes in v3?
In v2 clicked element was in this.element
```
beforeShow: function(){
	console.log($(this.element).data());
}
```

**Comment by mjcampagna** [comment]
```javascript
$.fancybox.getInstance().current.opts.$orig
``` 

Example:

```javascript
var a = $.fancybox.getInstance().current.opts.$orig;
console.log( $(a).attr('href') );
```

**Comment by fancyapps** [comment]
1) v3 does not have "beforeShow" callback, you can use "beforeMove" or "beforeLoad" callbacks, depending on your needs.
2) Most of the callbacks receive two parameters - instance and current group object. Example of how to get clicked element using callback:
```
beforeMove: function( instance, current ) {
	console.info( current.opts.$orig );
}
```

3) If you want to execute callback for every instance, you can do like this:

```
$(document).on('beforeMove.fb', function( e, instance, slide ) {
    // you code...
});
```

Some notes:
- variable name "element" was not self-explaining, therefore it was chosen to replace with "$orig" (as shortcut of "originallyClickedElement" :) )
 btw, v3 follows common naming convention to start variable names with `$` when the variable represents a jQuery object.
- "$orig" element can be passed as an option, therefore it is found under "opts". In v3, gallery object attributes (like "isLoaded") are separated from options (like "speed").
- be careful changing "current" object, because it is passed by reference. Therefore doing something like this will create unexpected result: 
`current.opts.caption += ' Something';`

In this case you can store original caption, for example, like `current.opts.origCaption = current.opts.caption;` and later use it to manipulate.

**Comment by mubasshir** [comment]
var element = $.fancybox.current.element; //returns jQuery object

**Comment by fancyapps** [comment]
@mubasshir That is for v2, but for v3 you need to retrieve instance object and then:

`$.fancybox.getInstance().current.opts.$orig` (corresponding element for current slide)

or

`$.fancybox.getInstance().$trigger` (clicked element)

Note: if you want to retrieve this from within a callback, then you already has access to instance object and current object, because they are passed to all callbacks (see previous answer for a sample)
