### ISSUE TITLE
Working with a data-srcset

### ISSUE THREAD

**Issue by aflipphi** [fancyapps/fancyBox#1203]
In our project we work with srcsets to show the correct image based on screensize.
Does Fancybox 3 support this option by for instance the use of data-srcset or it there and other way to accomplish this for a gallery ?

**Comment by fancyapps** [comment]
Not yet, it is in TODO list.

**Comment by sjoerdth** [comment]
Any idea on an ETA, or what the priority is on your TODO list? Would be a great (and essential) feature!

**Comment by fancyapps** [comment]
I actually cannot decide how to implement this, basically there are two options: 1) simply set "srcset" attribute for image tag and let the browser to do the rest 2) or parse "srcset" option value and set image "src" attribute according to window dimensions?

**Comment by sjoerdth** [comment]
Your first option so part 2 (https://ericportis.com/posts/2014/srcset-sizes/#part-2) of that blogpost is what I was thinking of. That way the markup and the way the browser handles things is 1 to 1 with how it works normally.

**Comment by fancyapps** [comment]
OK, the last commit contains a basic "srcset" support.  Example of usage:

```
<a data-fancybox="test-srcset"
   data-type="image"
   data-srcset="https://placeholdit.imgix.net/~text?txtsize=33&txt=small_640%C3%97427&w=640&h=427 640w,
                https://placeholdit.imgix.net/~text?txtsize=33&txt=medium_1200%C3%97800&w=1200&h=800 1200w,
                https://placeholdit.imgix.net/~text?txtsize=33&txt=large_1600%C3%97800&w=1600&h=960 1600w"
   href="https://placeholdit.imgix.net/~text?txtsize=33&txt=small_640%C3%97427&w=640&h=427"
>
	<img width="240" src="https://placeholdit.imgix.net/~text?txtsize=33&txt=small_240%C3%97160&w=240&h=120" />
</a>
```

See working demo - http://codepen.io/fancyapps/pen/bqbpbO?editors=1000

A few notes:

1) The script sets "srcset" parameter value for the image, the rest is up to the browser. The script is not changing image source or whatsoever on window resize.

2) The script is parsing "srcset" value anyway. It chooses the right initial src value, otherwise the browser (that supports "srcset") might download two files (one from "src" and one from "srcset").

3) When you are testing using Chrome, be aware that Chrome does not change image source dynamically. Disable cache or use firefox to see effect when resizing window.

4) This feature is currently not compatible with another feature: displaying thumbnail while the full size image starts loading. E.g., if you pre-define image width/height, users would see zooming animation of thumbnail and with fast internet connection, they would probably not see any loading animation.
But, to do some calculations, the script needs to know image dimensions and if you are using "srcset", you would need to somehow define dimensions for each source. The question is - how? There are a few possibilities but I have not yet decided that would be the best.

**Comment by fancyapps** [comment]
About the 4th point. I was thinking about using non-standard "srcset" syntax (like `srcset="large.jpg 1024h 768w, small.jpg 512w 384h"`; and why this is not standardized? who knows..), when it suddenly hit me. We actually do not need height for each image source, if we know image ratio! And we can calculate ration from default width/height values. I`ll update the code...

**Comment by fancyapps** [comment]
All right, I have refactored the code a bit and now it is possible to display thumbnail as preview image while full size image is loading, example:

```
<a data-fancybox="test-srcset"
	data-type="image"
	data-srcset="https://placeholdit.imgix.net/~text?txtsize=33&txt=1_large_1600%C3%97800&w=1600&h=960 1600w,
		     https://placeholdit.imgix.net/~text?txtsize=33&txt=1_medium_1200%C3%97800&w=1200&h=720 1200w,
	             https://placeholdit.imgix.net/~text?txtsize=33&txt=1_small_640%C3%97427&w=640&h=384 640w"
	data-width="1200"
	data-height="720"
	href="https://placeholdit.imgix.net/~text?txtsize=33&txt=1_medium_1200%C3%97800&w=1200&h=720"
>
	<img width="240" src="https://placeholdit.imgix.net/~text?txtsize=22&txt=1_thumb_240%C3%97160&w=240&h=144" />
</a>
```

and I have updated the demo - http://codepen.io/fancyapps/pen/bqbpbO?editors=1000

**Comment by sjoerdth** [comment]
Finally got around to testing and it working nicely!

I encountered one minor issue though, when you open the fancybox on a small resolution it loads the 640px width image (in your codepen demo), then when you enlarge the window the bigger images will load correctly, but the _fancybox-placeholder_ won't go past the width of the initially loaded image, so 640px in this instance.

**Comment by fancyapps** [comment]
@sjoerdth Yes, I`m aware of this issue. The problem is that I have not found a nice way to correctly get image size if it has srcset. See https://bugzilla.mozilla.org/show_bug.cgi?id=1230711 and https://github.com/whatwg/html/issues/381#issuecomment-163367578
Maybe I`ll implement a hack, but I am not sure.
