### ISSUE TITLE
Error installing plugin via NPM

### ISSUE THREAD

**Issue by oninross** [fancyapps/fancyBox#1209]
Terminal is saying 

`Cannot find module 'gulp-plumber-notifier' from ..\node_modules\fancyapps-fancybox`

**Comment by fancyapps** [comment]
There is currently no official fancybox package on NPM. 

Someone else forked fancybox v2, created package named "fancybox" and, while he is agreeing to transfer ownership, we are stuck, because he changed versioning and now NPM has package fancybox having version 3.0.0, but it contains fancybox v2, not v3!
