### ISSUE TITLE
Fancybox 3 doesn't work in IE8. Is it supposed to?

### ISSUE THREAD

**Issue by Phil-G** [fancyapps/fancyBox#1231]
`$('#MyImage').fancybox();`

> Object doesn't support property or method 'fancybox'

I don't actually have 8 on my machine. I tried this in IE11 using 8 emulation mode.

**Comment by fancyapps** [comment]
I feel sorry for you if you need IE8 support. fancyBox3 supports all major browsers, but IE8 is not among them. I think that nowadays it is more important to focus on mobile devices instead of legacy browsers.

Big players like youtube, facebook and even jQuery have already dropped IE8 support. And you can read on [Wikipedia](https://en.wikipedia.org/wiki/Internet_Explorer_8) that "Effective January 12, 2016, Internet Explorer 8 is no longer supported on any client or server version of Windows".

**Comment by mjcampagna** [comment]
>  I think that nowadays it is more important to focus on mobile devices instead of legacy browsers.

I agree wholeheartedly.

Welcome back, @fancyapps! I hope you're feeling back in good health.

**Comment by fancyapps** [comment]
Yes, I`m back :)
