### ISSUE TITLE
compensate-for-scrollbar does not work

### ISSUE THREAD

**Issue by leecollings** [fancyapps/fancyBox#1240]
Adding the class `compensate-for-scrollbar` to fixed position items does not stop the divs shifting when the scrollbar disappears when a fancybox is opened.

Upon inspection, no rule is added to the div, and no declaration of this kind is found within the CSS file

**Comment by fancyapps** [comment]
You will not find that rule within CSS file, because scrollbar width is different across browsers and therefore it is calculated and custom CSS rule is created.

About your issue - it is funny, because you write "fixed position items does not stop..". At first, I also did not notice that header/footer on your site are actually absolutely positioned (very strange, but maybe for a reason).

This fix was created for pages having fixed positioned elements. So, in your case, you do need to use "compensate-for-scrollbar" class. Simply remove " width: 100%;" rule and add "right: 0;".
