### ISSUE TITLE
could you please share 

### ISSUE THREAD

**Issue by harabara85** [fancyapps/fancybox#1255]
Thanks for your job, it's great plugin.
But i have not deep knowledge in JS.
Could you please share your "Customized layout" in codepen
thanks!
![fancybox](https://cloud.githubusercontent.com/assets/16612522/23560173/f642518a-0052-11e7-881d-c630da82e783.jpg)

**Comment by fancyapps** [comment]
It is all about CSS :) You see, the layout of v3 is just like lego, you can move them around or resize as you need. I`ll make a codepen demo.

**Comment by harabara85** [comment]
thanks, could you please show something like that
![fancybox](https://cloud.githubusercontent.com/assets/16612522/23577051/8653d6ea-00c6-11e7-9f10-8eb8fe34bf4e.jpg)

**Comment by fancyapps** [comment]
Here is a codepen demo for your layout - http://codepen.io/fancyapps/full/XMKjrJ/

You just have to choose how you get content for that fixed section. In this demo I chose to use "data-fancybox" attribute value from links to find element containing the content. E.g., links have `data-fancybox="images"` attribute and content is hidden inside element having `id="images-info"`.

Also, it probably would be better to use LESS (or any other css preprocessor) to create custom layout. Because the width of that new block ("20vw" in my example) is used in multiple places

**Comment by harabara85** [comment]
great!!!
thnks a lot!

**Comment by fancyapps** [comment]
The same as in v2, the easiest way is to show one image and others put inside hidden container.
See this demo (from documentation): http://codepen.io/fancyapps/pen/jyEGGG/?editors=1000
