### ISSUE TITLE
Update fancybox version on cdnjs

### ISSUE THREAD

**Issue by glowworms** [fancyapps/fancybox#1260]
CDNJS is currently hosting the version 2.1.6 as the highest version.
https://cdnjs.com/libraries/fancybox

Can you please get them to update to the version 3.
Thank you.

**Comment by glowworms** [comment]
I've submitted a request to get them to update their version.

https://github.com/cdnjs/cdnjs/issues/10802

**Comment by fancyapps** [comment]
Hi,

Thanks for contributing. I guess we need to wait a bit for CDN services to pick up v3. 

Unfortunately, there is no official npm package of fancybox. There is one package named "fancybox", but it is a modified fork by someone else. I contacted the author about transferring the ownership, but he says he can not do that due to version mismatch (he made a few changes to v2.1.5 and released it as v3.0.0).

**Comment by fancyapps** [comment]
They finally added v3 to the cloud!  ☁️ 😄  See - https://cdnjs.com/libraries/fancybox 

It is a bit outdated version, but do not worry, it will be updated.
