### ISSUE TITLE
css styling of content/image/image-border

### ISSUE THREAD

**Issue by luftfisch** [fancyapps/fancybox#1263]
The new minimal style of V3 looks great on mobiles but I miss a white image border on larger desktop screens. Is it possible to add a border style to the image to keep a similar look as on V2? I tried adding a border style  to the class .fancybox-image but then I have a strange behaviour of the opening and closing animation.

**Comment by fancyapps** [comment]
Hi,

I would love to add an option for that white border, but the problem is with animation performance. You see, v2 and the early versions of v3 used to animate top/left/width/height CSS properties, but that lead to poor performance. It improved after switching to CSS transform property, but that brought another problem - everything scales, including borders and outline. That is why you see some strange behavior and I do not see any possible solution to this.

On the other hand, thanks God there is currently flat design trend and users generally seem to be happy about this minimalistic design.
