### ISSUE TITLE
Accelerator support for mobile phones

### ISSUE THREAD

**Issue by Tusko** [fancyapps/fancybox#1264]
Hey, thanks for a great plugin. I've used fancybox from the first version :)
How do you think, is it have the sense to add the option to control the gallery accelerometer on your phone?
For example, tilt phone when an image is zoomed, or shake the phone to navigate prev/next image.

I would like to hear your opinion.
Thanks)

**Comment by fancyapps** [comment]
Hi! If you wish and somehow can detect phone tilting/shaking, you can use API (http://fancyapps.com/fancybox/3/docs/#api) to change gallery images.

I do not thing that something like that will included by default, because swiping through images is much easier and faster. Users probably would not be aware of this feature and would not use it anyway.
