### ISSUE TITLE
Image dimension issue

### ISSUE THREAD

**Issue by iMerica** [fancyapps/fancybox#1266]
Hi,

All my images served from my CDN (Cloudinary) are not displaying properly. The following test photo
![ujk0vfxpx6zkcsotnpuf](https://cloud.githubusercontent.com/assets/487897/23783321/99e6d778-050f-11e7-9d62-20ed808c06c1.jpeg)

is displaying like this:

![fancybox-issue](https://cloud.githubusercontent.com/assets/487897/23783327/a8fcef68-050f-11e7-9b5d-98b84a1f80a4.png)

Granted, my images are all quite large, but I'm expecting FancyBox to constrain the dimensions appropriately so that images of any dimensions or aspect ratio display properly on any viewport.

Thanks,

Michael

**Comment by iMerica** [comment]
I was able to fix this by adding `data-type="image"` since Cloudinary doesn't provide an extension, fancybox was probably not able to determine the content type.

**Comment by fancyapps** [comment]
The script will try to guess content type from url, but it fill fail for urls like "showimage.php?id=123". In such case, it will load content into iframe, because it is safe, you can put inside iframe almost everything, including imges (but they will not resize correctly, though).

I am now thinking that I will change fallback content type to "image", because quite a number or users get confused when images are not displaying as expected.
