### ISSUE TITLE
Fancybox3 with select2 (focus - too much recursions)

### ISSUE THREAD

**Issue by nino-s** [fancyapps/fancybox#1270]
There is a issue using fancybox 3 with select2:

ATM if a select2 is opened/closed the focus event of fancybox is called. Fancybox calls the focus of the first element. If the first element is a select (with select2) the focus event of select2 is called. After this focus is called, the fancybox focus is called again, resulting in a too much recursion error.

I thought to just disable the focus event via the defaults fancybox settings, but their is no check on the focus key. (only images sliding complete checks for `current.opts.focus`)

I would like to give a example via jsfiddle, but fancybox 3 is not availabe via cdn yet :)

**Comment by nino-s** [comment]
@fancyapps 
On line 1956 you have the focus function:

```js
        // Try to find and focus on the first focusable element
        // ====================================================

        focus : function() {

            var current = this.current;
            var $el;

            $el = current && current.isComplete ? current.$slide.find('button,:input,[tabindex],a:not(".disabled")').filter(':visible:first') : null;

            if ( !$el || !$el.length ) {
                $el = this.$refs.container;

            }

            $el.focus();

            // Scroll position of wrapper element sometimes changes after focusing (IE)
            this.$refs.slider_wrap.scrollLeft(0);

            // And the same goes for slide element
            if ( current ) {
                current.$slide.scrollTop(0);
            }

        },
```

You should check for `self.opts.focus` on Line 1968 `$el.focus();`. Shouldn't you?

**Comment by fancyapps** [comment]
This option is checked before calling `focus()` method (after content is revealed).

What the current version lacks is something like `trapFocus' option, because the script listens to "focusin" event. Maybe this is what causes your issue.

**Comment by nino-s** [comment]
I am sorry - your right, this is releated to the `focusin` event and something like a `trapFocus` option would indeed help.

**Comment by fancyapps** [comment]
Btw, I figured out why select2 is causing this issue. You see, fancyBox tries to act as "true" modal by default (many people have asked for this) - it traps focus and does not allow user to focus outside the modal.
Otherwise people would be able to just press "tab" and navigate to different parts of the page.

The problem is that select2 appends absolutely positioned element to the page "body" element and then tries to set focus. Obviously, fancyBox does not want to allow and sets focus back to the modal, because that element (created by select2) is outside. And so it goes loops.

Luckily, this is easy to fix, just change position of that element created by select2:

```JS
$(document).on('onComplete.fb', function( e, instance, current ) {

  current.$slide.find('select').select2({
    dropdownParent: current.$content
  });

});

```
See demo - http://codepen.io/fancyapps/pen/ZeXKev

I think this is a good solution, because if you would disable focus trapping on fancyBox, then it would be no more "true" modal.

Another solution maybe would be to somehow stop select2 to autofocus, but there doesn't seem to be an option for that.

**Comment by nino-s** [comment]
You are right, thanks for your alternative solution and for digging into it. Currently i stopped the search field focus which also works quite well:

```js
$(document).on("focus", '.select2-search__field', function(e) {
    e.stopPropagation();
});
```

This issue only occurs if select2 is the first element. I think you can close this one - these alternatives show a way to fix it, if someone else has the same problem.

**Comment by fancyapps** [comment]
Hi, This should work fine in v3.1.
