### ISSUE TITLE
Fancybox 3 Thumbnails

### ISSUE THREAD

**Issue by smaddy** [fancyapps/fancybox#1279]
The position of the thumbnails was way better in the beta. Any chance to get them back to the bottom and always showing them by default?

**Comment by fancyapps** [comment]
Hi, You can customize position using CSS and use "showOnStart" option to display on start, check this example: http://codepen.io/fancyapps/full/vgRajd/

**Comment by lordrak007** [comment]
Thank you for your answer but is it possible disable grid and show one centered line which move on another page linke in 3beta?
Thanks you very much

**Comment by fancyapps** [comment]
@lordrak007 The problem is that I like both designs, but the benefit of the current one is that user can see all thumbs and easily scroll or swipe the list. I could, of course, implement both and create an option to switch them, but that would increase file size and some people are already complaining about that. 
Maybe in future I will create a separate module so you could build your own version of fancybox using gulp.

Anyway, here is demo using v3.1 - https://codepen.io/fancyapps/pen/PjYPMw

**Comment by AlexanderMatveev** [comment]
Now Fanybox has thumbs.axis option. But looks like it does not working - thumbs still shown at right, not bottom of modal.

**Comment by fancyapps** [comment]
You have to add some extra CSS for that to work correctly, see the demos.

**Comment by lloydbanks** [comment]
**fancyapps**, could you please provide an updated example for the last version? (v3.5)

btw, I believe it's not logical behaviour of `axis: 'x'`. This config property name clearly tells us to place thumbnails at the bottom of the screen and there should not be any extra css to fix this bug (yes, I consider this a bug).
Also thumbnails from the right decrease the full image size on an already small mobile device, so in my opinion it shoul be at the bottom by default.

Thanks.

**Comment by fancyapps** [comment]
The idea of fancybox is that you can use it as a tool to build something ... great. That options just tells the script to add additional wrapper so that horizontal scrolling works. You can then use CSS to position each block wherever you want and what size you want, for example, like this - https://codepen.io/fancyapps/full/xWqNZK/

**Comment by AlexanderMatveev** [comment]
@fancyapps I'm agree with @lloydbanks. Fancybox was always a super-easy and useful plugin, "install and enjoy" :wink: I really hope it always be this way, because touch devices support is mainstream now :wink:

**Comment by mjcampagna** [comment]
@lloydbanks, horizontal should not be the default. It would change or
outright break all existing implementations if such a change were made now.

As someone who has heavily customized and extended Fancybox 3 for my own
implementation, I agree with @fancyapps, and appreciate the high degree of
customizability that’s been built into Fancybox 3. Kicks the crap out of
every other light box, and I’ve tried them all.
