### ISSUE TITLE
Events / Callbacks

### ISSUE THREAD

**Issue by fredleput** [fancyapps/fancybox#1306]
Hi,

Can someone explain me what's wrong with my event handler please.

`
function fancyboxComplete(e, instance, slide) {
		alert('coucou');
	}
	document.addEventListener('onComplete.fb', fancyboxComplete, false);
`

Thx Fred.

**Comment by fancyapps** [comment]
Since you are using jQuery anyway, you can bind events like this:

```JS
$(document).on('onComplete.fb', function( e, instance, current ) {
	console.info('It works!');
});
```

**Comment by fredleput** [comment]
Thx, it works but is it possible without jQuery ? This is what i'm looking
for...

Fred

2017-03-20 17:57 GMT+01:00 Jānis Skarnelis <notifications@github.com>:

**Comment by fancyapps** [comment]
These are custom events and are fired using jQuery. Looks like they are not caught when using native method - https://bugs.jquery.com/ticket/11047

**Comment by fredleput** [comment]
Thx for this information, i didn't knew that. ;)

Fred

2017-03-20 18:06 GMT+01:00 Jānis Skarnelis <notifications@github.com>:

**Comment by fancyapps** [comment]
Yes, that is very unfortunate. I was not aware of this, too. It turns out that if you bind event like this: 

`document.addEventListener('abc', function() { console.info('abc'); }, false);`

Then triggering them using jQuery will not work as expected:

`$(document).trigger('abc');`

But this works:

`document.dispatchEvent( new CustomEvent('abc', {} ) );`

I`ll make some tests and probably will update the code to make it work.

**Comment by fredleput** [comment]
Great !

Fred

2017-03-20 18:39 GMT+01:00 Jānis Skarnelis <notifications@github.com>:
