### ISSUE TITLE
Class attribute

### ISSUE THREAD

**Issue by xApep** [fancyapps/fancybox#1325]
Hi.
Is it possible to use attribute to add "baseClass"? Would be nice to have one init for fancybox and than you can set different fancybox baseClass on the "fly".

**Comment by mjcampagna** [comment]
$.fancybox.getInstance() seems to be unavailable at the time baseClass is processed, so that's not the way. Instead, we can use callbacks to set attributes to the container.

```html
<a href="image.jpg" data-class="my-custom-class">Image</a>
```

```javascript
$(document).on({
	'beforeMove.fb' : function(e, instance, item) {

		var a = $.fancybox.getInstance().current.opts.$orig,
		container = $.fancybox.getInstance().$refs.container,
		dataClass = a.attr('data-class');

    if ( dataClass != undefined ) container.removeAttr( 'data-class' );
    container.attr('data-class', dataClass);

	}
});
```

In this case, I'm using an HTML5 'data-' attribute rather than class, as it's easier to clean up on each change.

You can style each with:

```css
a[class="my-custom-class"]
```

**Comment by xApep** [comment]
Thanks!

**Comment by modulbuero** [comment]
In Fancybox 3, if you open fancybox via link, you can just add

> jQuery(this).attr("data-base-class",'fancy-search')
