### ISSUE TITLE
Iframe - Autoheight

### ISSUE THREAD

**Issue by xApep** [fancyapps/fancybox#1328]
Hi. I just can't figure out how this works. I have iframe where I want that fancybox height is fited to iframe content height.

I've try to put this "parent.jQuery.fancybox.getInstance()" to iframe but nothing happens.

Any advice would be more than welcome. Thanks!

**Comment by mjcampagna** [comment]
There's no good or native way to size an iframe according the size of it's contents. This is not a shortcoming of Fancybox; it's just the nature of iframes. You could try something like Pym.js, but whether or not that will works depends on what type of document you're embedding, as well as how nice it wants to play with Fancybox.

**Comment by fancyapps** [comment]
@xApep fancyBox tries to detect content dimensions and update iframe height automatically. If it fails, it means it can not access the content. Your page and iframed page must have same domain, port, etc - https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by xApep** [comment]
Well I have full control of the iframe content. Im using it for some forms on website so I can put everyhing in iframe content.

**Comment by fancyapps** [comment]
:)  Are you sure that Same-origin_policy restrictions are not applied? Maybe you are forcing iframe to custom size? Anyway, a live demo would help, otherwise, it is a shot in the dark.
Can you provide a link to your page?

You can see how it works on the homepage - "Iframed page" demo demonstrates iframe auto-size.

**Comment by xApep** [comment]
Here is the [example](http://dev.edsolution.si/adria_holidays/en/special-offers/d/glamping-resort-ramsak.html). Below Book now there is a send inquiry link; on click fancybox iframe opens.

Also I've notice that if the screen is smaller, iframe content has no vertical scroll, even when setting manual init:
            iframe : {
                preload : true,
                scrolling : 'yes'
            }

Thanks.

**Comment by fancyapps** [comment]
Looks like the script is not able to calculate dimensions of your content, because of the weird CSS rules you have on your page. Everything has "float:left" and "height: 100%", including body element. 

The script is able to correctly calculate height after removing these rules from body and wrapping element around content.

**Comment by fancyapps** [comment]
btw, your page shifts when opening/closing fancybox due to the same problem, why on earth your body has float:left and width: 100%;? Why? No, really, why? Does this really make sense to you?

**Comment by xApep** [comment]
Hehe you got that right...some old foundation stuff. After cleaning the sh***, everything works like charm. 

Thanks!
