### ISSUE TITLE
Keep thumbnails feature for mobiles

### ISSUE THREAD

**Issue by klihelp** [fancyapps/fancybox#1333]
Regression swiping from first item trough all to the last item .. #

**Comment by fancyapps** [comment]
I`m sorry, I can not understand your commend.

**Comment by klihelp** [comment]
Thanks for "asking" nicely about my issue and "keep the issue open" until confirmation.

As tested back in March, thumbnails were hidden for small screens as mobiles.

**Comment by fancyapps** [comment]
Yes, they are hidden by default if screen size is smaller than 800px as there is a little space for them.

But, you can use CSS to force to display thumbnails or maybe change position.

But what did you mean by "Regression swiping from first item trough all to the last item .. #" ? And how does it relate to thumbnails? That is a mystery to me. And did you really need to thumb down my comment because of that? - Another mystery to me.

**Comment by fancyapps** [comment]
btw, if you are interested, I would like to hear your thoughts and suggestions - https://gitter.im/fancyapps/fancybox

**Comment by klihelp** [comment]
Thanks, if that easy then having an option to show/hide thumbnail for small screens would be just good for many devs.

Imagine how it is when using Fancybox for a large collection of images, eg. 100 items, and not having the thumbnails on mobile. Visitor who wants to check certain images have to either walk trough back-and-forth all images between desired images; or close-and-reopen the popup which is a lot of extra steps.

**Comment by fancyapps** [comment]
hmm, you are right, I`m now thinking about changing that.
