### ISSUE TITLE
Fade between slides instead of animating?

### ISSUE THREAD

**Issue by seabasss** [fancyapps/fancybox#1336]
Hey,

Is there an easy way to fade between slides instead of having them animating sideways?

Thank you!

**Comment by fancyapps** [comment]
Hi,

I`m working on this right now - http://imgur.com/a/EfhzQ

**Comment by seabasss** [comment]
Cool! With some different options, like a plain fade? :) thanks!

**Comment by fancyapps** [comment]
@seabasss There will be, of course, some default animations like fade. The goal is to enable users to create animations with CSS.

**Comment by mjcampagna** [comment]
I would love to have separate transitions for desktop and mobile -- I.e.
Fade on desktop, but move (as current) on swipe.
-- 

--
Matthew Campagna
The Turning Gate | http://theturninggate.net
Photographers Plugins and Resources

**Comment by Pro** [comment]
Any update on this? Is there already test code?
I would like to use FB3 for simply fading between images (opacity) with a predefined transition speed without any transformation.

**Comment by fancyapps** [comment]
@Pro You can get code here https://github.com/fancyapps/fancybox/tree/3.1 and preview here - http://codepen.io/fancyapps/pen/LyNXqr

**Comment by Pro** [comment]
Nice! Works perfectly, and so easy! very good work 👍

**Comment by Pro** [comment]
One minor thing:
During fading, the original content of the page can be seen very weakly through the image. I think this is because the current image is faded out during fadein of the new image. Therefore in the middle of fading, both images have 0.5 opacity and thus the background shines through.
Is there an easy way to fix this?

I.e., the current image should just stay there, the new one fades in over the current image, and then after fading finished, the old image can just be hidden.

**Comment by fancyapps** [comment]
@Pro Your scenario would not look great if images would have different aspect ratio.

I see two possible solutions:
1) Make fading-in much faster than fading-out. For example, if default transition speed is 300ms, then this snippet would make fading-in twice fast and background would not be noticeable during transition:
    ```CSS
    .fancybox-fx-fade.fancybox-slide--current {
	  opacity: 1;
	  transition-duration: 150ms;
    }
    ```
2. You could play with easing so that slides would have higher opacity in the middle of transition:
    ```CSS
    .fancybox-fx-fade {
	    transition-timing-function: cubic-bezier(.19,1,.22,1);
    }
    ```

Of course, third option would be to set solid color to fancybox background so that page content would not be visible at all.

**Comment by fancyapps** [comment]
Slides now fade by default when navigating gallery.
