### ISSUE TITLE
Possible to close fancybox when user hits browser back button?

### ISSUE THREAD

**Issue by rrcdr** [fancyapps/fancybox#1436]
The hash feature isn't quite what I'm looking for. I'm just wondering if you can think of any way to get the browser back button to close fancybox.

**Comment by fancyapps** [comment]
I was very confident that this is not possible, but to my surprise, it is:

```JS
// If pressed back button
$(window).on('popstate', function (event) {
	if (event.state!==null) {
		$.fancybox.getInstance('close');
	}
});
```

This will be included in the next commit.

**Comment by fancyapps** [comment]
I hope it now works as you expected.

**Comment by rrcdr** [comment]
Hi,

I'm not seeing any difference with the latest commits. If I have a fancybox instance open and hit the back button, the browser still navigates back to the previous page in the history. I was hoping it would just close fancybox and stay on the same page.

**Comment by fancyapps** [comment]
fancyBox will be closed if you press back and later forward. It is not possible to prevent actual navigation away from current page.

**Comment by rrcdr** [comment]
Thanks!

**Comment by rrcdr** [comment]
Hmm on my end, it doesn't behave as you describe. On a page with fancybox open I press the back button which brings me to a previous page, then I press the forward button and it goes back to the original page with fancybox still open.

**Comment by fancyapps** [comment]
Uh, sorry, looks like I did not understood correctly the description -
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate

**Comment by fancyapps** [comment]
But of course, silly me, I had to simply use "unload" event :) Please, wait for next commit.

**Comment by fancyapps** [comment]
@rrcdr check now. And thanks for the patience :)

**Comment by rrcdr** [comment]
Hi,

After disabling turbolinks I can see it working as you describe.

I wonder if there is some way to get the functionality I am looking for perhaps with a hash type feature. Basically I am looking for similar functionality as instagram when viewed on desktop. It looks like when you click a picture, that picture has a unique url. You can scroll through some pictures but anytime you click back the picture viewing closes.

**Comment by fancyapps** [comment]
Well, instagram uses react and their lightbox is like a new page with a new entry in the browser history. 

When I created hash module, I tried to add this feature and you can see it (for now) on the homepage - http://fancyapps.com/fancybox/3/ - try to open any image and then press browser back button. It works as expected. But the problem starts when you keep pressing back and forward buttons, because that newly created entry in history still exists and therefore modal keeps opening. And there's no way to delete a history entry.

But, while I am writing this comment, I got an idea how to overcome this.. I`ll try to implement and will see how it goes :)

**Comment by fancyapps** [comment]
Last commit contains another attempt to solve this. 

But I think that it is just not possible to solve it perfectly. Because you can not modify url within window unload event, you can not bind click event on browser buttons. All you can do is to play with browser history. 

Right now fancybox adds new history entry on first open and modifies it after changing gallery items. This allows user to return to previous state (e.g., previous history entry) by clicking back button. Clicking forward will open fancybox again, because user navigates to history entry created by fancybox.

**Comment by sinjuangajan** [comment]
Yeah I have the same issue with browser back button. image popup again when i clicked browser back button. there shows too many history states as much you clicked gallery images to reach previous page.

**Comment by fancyapps** [comment]
@sinjuangajan are you sure you are using the latest version? The latest just creates one history entry.

**Comment by leszekb22** [comment]
Hello from Poland! I have the same problem
Please see demo
http://staw.bieleccy.com.pl/str_2010_touch_new.html

I using the latest version in the www.

**Comment by leszekb22** [comment]
Hello from Poland! 
Will the problem be solved?

**Comment by fancyapps** [comment]
Sorry, but what problem? Can you describe what steps you take, what is expected outcome and what are actual results?

**Comment by leszekb22** [comment]
Hello :) 
This problem described  sinjuangajan:
Yeah I have the same issue with browser back button.  image pops up again when i clicked browser back button. there shows too  many history states as much you clicked gallery images to reach previous  page.
--
On my website is exactly the same
http://staw.bieleccy.com.pl/str_2010_touch_new.html

Please take a look at some pictures and then press the back button several times.
The entire history of the viewed photos will be displayed.

**Comment by fancyapps** [comment]
Have you tried upgrading to the latest version?

**Comment by leszekb22** [comment]
I think so! Please check out my website source

**Comment by fancyapps** [comment]
You are using v3.0.47 but the latest is v3.1.20 - https://cdnjs.com/libraries/fancybox

**Comment by leszekb22** [comment]
It is problem??????
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.js"></script>

solution???
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.20/jquery.fancybox.min.js"></script>

**Comment by leszekb22** [comment]
I inserted a new link.
But now there are no pictures at all.

**Comment by sinjuangajan** [comment]
I think I am using latest version fancyBox v3.1.20. I am using an Instagram plugin in page. please check the link.
[Fancybox Link](http://graphicpot.com/fancybox/)
