### ISSUE TITLE
Caption custom position

### ISSUE THREAD

**Issue by bat-ruslan11** [fancyapps/fancybox#1449]
Good day! How can i put caption under the photo? Using "baseTpl" it's impossible, but mb you have custom solution?

**Comment by fancyapps** [comment]
Hi,

It depends on what you understand by "put caption under the photo".

1) If you are looking for something like in v2, then - sorry, there is no such option. You see, it is not possible to use CSS to specify element (like image) height depending on other element (like caption) height. But caption height varies depending on viewport width, too. And therefore v2 has complex algorithm that resizes caption and content to fit both inside viewport. v3 avoids that and this allows you to more easily control content dimension using CSS, build more complex layouts, etc.

2) If you know caption height, then you can simply push content from bottom using margin option so that content does not overlap caption.

**Comment by rouviere** [comment]
Hi fancyapps. I have been working with FA3 and I too have concerns about caption positioning. By default it is at the bottom and is not always noticeable - especially if the image does not take up the full screen. It is possible to move it to the top, but that is equally problematic. Because of varying screen sizes it is problematic to set absolute positioning. Is there any way to set it in relation to the image? That would be ideal.

Thanks.

**Comment by frederikvdbe** [comment]
Hi fancyapps. Is there still no way to inject the caption in the .fancybox-content container?
I've tried using the beforeShow event but somehow the slide.$content is undefined (on the first slide). The event 'afterShow' works but it's kinda wierd that the caption gets added after the animation is done...

Thanks in advance!

**Comment by emage** [comment]
I'm looking for a way to also better control the caption - as my caption overlaps the image above it.  Being that we do translation across various languages -- a fix caption height is not optimal. A way to maybe offset the image base on the calculated caption height
