### ISSUE TITLE
fancybox-3 instance don't have api methods

### ISSUE THREAD

**Issue by chim0380** [fancyapps/fancybox#1456]
I use fancybox 3
I wanted to open slide from code by API  but can't to do it. 

**HTML**
```
<a data-fancybox="group" href="http://test.png" ><img src="http://test.png" /></a>
<a data-fancybox="group" href="http://test2.png" ><img src="http://test2.png" /></a>
```

**JS**

> var $instance= $( '[data-fancybox]' ).fancybox({});

**Problem**
Object  $instance don't have API methods : next, open, activate  etc.

console.log($instance)    showed only  collection A elememts

Although I solved problem by   

> $instance[number].click()

I think  there is some problem in code.

**Comment by fancyapps** [comment]
Looks like there is some misconception, you probably expect that fancyBox works just like a typical jQuery plugin. But it is does not, because it is not a typical plugin :)

When you call `$('selector').fancybox()` then you just add click event on your selected elements. Inside that event `$.fancybox.open();` is called that creates and returns new instance.

So, you probably are looking for something like this:

```
// Create new instance
var instance = $.fancybox.open( $('[data-fancybox="gal-psa"]') );

// Use instance API
instance.next();
```

**Comment by fancyapps** [comment]
Oh, sorry. I did not understood why ask this question at first. But then I realized that documentation has wrong example about getting instance.

When you call `$('selector').fancybox()` then you just add click event on your selected elements. Inside that event `$.fancybox.open();` is called that creates and returns new instance.

So, what you need to do is something like this:

```
// Create new instance
var instance = $.fancybox.open( $('[data-fancybox="gal-psa"]') );

// Use instance API
instance.next();
```
