### ISSUE TITLE
Padding?

### ISSUE THREAD

**Issue by ffolkes** [fancyapps/fancybox#1464]
Thank you for such a beautiful and...fancy...way to show photos! :) I noticed the padding option no longer works. I used to use this to give enlarged content a thick white border (as if matted). I tried to do this on v3 by changing the CSS, but nothing worked out. Is this still possible? Thanks. :)

**Comment by fancyapps** [comment]
Hi, Thanks.

If by "content" you mean images, then sorry, no. 

While you could, of course, add border around images (using CSS, something like "border: 20px solid #fff"), the problem is related to zooming. The script uses CSS "transform: scale" to improve animation performance, consequently, everything scales, including padding/border and shadows and it looks bad.

The solution would be:
1) animate top/leftwidth/height properties instead of translate - poor performance (https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/)
2) run two animations simultaneously - one for zooming (white) background element, one for image.

Maybe in future, if lots of people would ask for this, I might go with 2nd option, but that would create another layer of complexity and I would like to avoid that :) There might be problem with performance, too.

**Comment by capnhairdo** [comment]
Well, if you're collecting votes, I would love to see this option added as well. Like ffolkes, I've been struggling to figure out a way to do this and ran into the very problems you listed above.

**Comment by acwolff** [comment]
I do that in [my jAlbum FancyBox skin](https://jalbum.net/en/skins/skin/FancyBox) by applying a filter which adds a white border into the image, see [this demo album](https://andrewolff.jalbum.net/FB_FixedShapeThumbs/). More info on [my blog](http://andrewolff.blogspot.com/2014/07/how-to-use-borders-and-frames-with.html).
