### ISSUE TITLE
Back Button Issues / Don't change URL

### ISSUE THREAD

**Issue by relish27** [fancyapps/fancybox#1468]
Hello,
I do really like the new version of Fancybox in many ways.  However, since implementing this, we've found one usability issue: Because the URL changes when you navigate through the images, it messes up the flow if someone wants to look at a gallery item and then navigate back to a previous page.  The experience is like this:

1. Go to a product page with an image gallery
2. Click on an image thumbnail
3. Navigate through the fancybox gallery
4. Click out of the popup/overlay so that the product page is visible again
5. Click the back button to go back to view a different product
6. What the user expects at this point is to go back to the page they were at before step #1 above.  However, they end up on the last fancybox overlay view and have to click through all images that they've seen before they can get back to the previous page.  

Is there a way to disable the URL updates so that the back button works as expected?  I do get that it's nice to be able to link directly to a specific image.  But in this case I think the value is negated by this user experience situation.

Thanks!

**Comment by fancyapps** [comment]
Hi,

I assume you are using version from 3.0 branch, could you improve to the latest (v3.1.x) ?

**Comment by eaxexe** [comment]
I am experiencing the same issue as @relish27

V3.1.x (Newest version, downloaded and set up 5 minutes before writing this), fixes some of it, but an overall option to completely disable the changing of the url would be very very nice.

Thanks 😄

**Comment by nebrot** [comment]
See docs: http://fancyapps.com/fancybox/3/docs/
If you wish to disable hash module, use this snippet (after including JS file):
`$.fancybox.defaults.hash = false;`

**Comment by fancyapps** [comment]
As I have already commented in other issues related to hash module - this will never work perfect, because the script adds new history entry on first opening (so you can close it by pressing back button, e.g., navigating to previous history entry) and it is not possible to remove it afterwards (e.g., clicking forward will navigate to previously added history entry by the script).

You can disable in 3 ways:
1) Fork project and build your own js file excluding hash module;
2) Changing defaults - `$.fancybox.defaults.hash = false;` 
3) or simply setting `hash : false` when initializing fancybox.
