### ISSUE TITLE
$.fancybox.getInstance().Thumbs.close()

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1480]
Hi,

I'm using $.fancybox.getInstance().Thumbs.close(), and finding that the method is not removing the 'fancybox-show-thumbs' class from the container, as I believe it should do.

Also, after using this to close the thumbnails, I'm not able to open them again. Hitting the Thumbs button doesn't seem to work.

**Comment by fancyapps** [comment]
Hi,

I remember that I removed "close" method (but forgot to update docs, sorry about that), because it seemed to duplicate "hide" method. I think the initial idea behind "close" method was something like "destroy" method would do (e.g., remove everything and clean up), but not sure that anyone really needs that.

**Comment by mjcampagna** [comment]
Cool. Using $.fancybox.getInstance().Thumbs.hide() gets the job done then. Thanks!
