### ISSUE TITLE
.setContent() doesn't permanently update slide content

### ISSUE THREAD

**Issue by tlepelaars** [fancyapps/fancybox#1515]
$.fancybox.getInstance().setContent() changes content for the current slide but it doesn't seem to permanently update the slide content (if you navigate away from the slide and come back to it you see the original content and not the updated content).

I searched through the code and it seems that this is the way its supposed to work ? Is there any way to update the instance object so that the slide is updated permanently without having to close and re-open the gallery ? I tried updating the $.fancybox.getInstance().group array but that didn't work.

Thank you !

**Comment by fancyapps** [comment]
Hi,

Sorry, this is how it works, the API was not designed to allow slide content/type change, but this might be updated in future, if more users would ask for this feature.

When creating new slide, the script takes corresponding object from `group` array and then loads content depending on the content type. The script creates and loads only 3 slides and removes unnecessary slides after navigating. Traditional sliders create and preload all slides, but this is not good idea for lightbox type scripts, because loading too many images would quickly fulfill the memory.

So, if you want to permanently change content of the slide, you have to update object inside `group` array and slide object too, if exists.

Example:

```JS
$("#test").on('click', function() {
  var fb    = $.fancybox.getInstance(),
      slide = fb.current,
      props = {
        isLoaded : false,
        src      : '#hidden-content-b'
      };
    
  // Update group array
  $.extend( fb.group[ slide.index ], props);
  
  // Update current slide object
  $.extend( slide, props );
  
  // Load content into current slide
  fb.loadSlide( slide ); 
});
```

Demo : https://codepen.io/anon/pen/YQvrKb?editors=1010

**Comment by ivanmoralesv** [comment]
@fancyapps I need to change the content of an ajax slide inside the slide (with another ajax content). instance.setContent() doesn't work for me, but doing the way you propose it works.

The only thing I don't know how to do, is to bind events to the new loaded slide. I tried to send in "props" the afterShow function like:

```
var props = {
	isLoaded : false,
	type: 'ajax',
	src: src,
	filter: filter,
	afterShow: function(){
		bindLightbox('#ajax-wrapper');
	}
};
```
But it doesn't work 😞

**How I can know when the new slide is loaded?**
Thanks in advance!

**Comment by fancyapps** [comment]
Hi,

I have updated the demo that show how to pass custom options:

```JS
$("#test").on('click', function() {
  var fb    = $.fancybox.getInstance(),
      slide = fb.current,
      props = {
        isLoaded : false,
        src  : '#hidden-content-b',
        opts : {
          afterLoad : function() {
             console.log('Success!');
          }
        }
      };
    
  // Update group array
  $.extend( true, fb.group[ slide.index ], props);

  // Update current slide object
  $.extend( true, slide, props );

  // Load content into current slide
  fb.loadSlide( slide ); 
});
```
