### ISSUE TITLE
Support SVG graphics

### ISSUE THREAD

**Issue by ca-dsgn** [fancyapps/fancybox#1521]
I am using fancybox for svg files, but it seems like that fancybox is not viewing svg files correctly in Chrome and Firefox. In Safari the Zoom-Effect works like expected. In Firefox I don't see any image when clicking on it. In Chrome it is much too small.

https://codepen.io/christian-albert/pen/ZymLPj

**Comment by fancyapps** [comment]
Hi,

Sorry, svg files are not (fully) supported. I am not event sure that it is possible to correctly determine width/height of svg element, because, well, it is "Scalable Vector Graphics".

**Comment by odahcam** [comment]
In SVG you can define the width and height and you don't loose any scaling feature by doing this. So that could be a required thing by fancyBox to support SVGs and know their width.

**Comment by fancyapps** [comment]
Anyway, you can always put your svg element into some wrapping element and display it instead (like any other "inline content").

**Comment by odahcam** [comment]
You can even include your SVG with a `<img>` tag.

**Comment by pixonti** [comment]
I just target whatever size I want for the svg in the anchor tag with data-width and data-height. The src of the tag can be an svg file. Be aware that svg files that have transparency will have the Fancybox background. If designed correctly, it makes for a wonderful effect of a graphic hovering over the page. I've tested this in multiple browsers that support svg files.

**Comment by infatum1** [comment]
Really need SVG support for the periodic table - http://chemistrytable.scienceontheweb.net/index_eng_svg.php 

Have a hyperlink wrapped around and SVG rect element
`<a href="elements/H.php"><rect x="48.9" y="84.3" class="st0 fancybox fancybox.iframe" width="96.3" height="96.3"/></a>`

Tried this as well -
`<a class="fancybox fancybox.iframe" href="elements/H.php"><rect x="48.9" y="84.3" class="st0" width="96.3" height="96.3"/></a>`

To no avail. The iframe doesn't load properly. 

According to www.w3.org,

Multiple class names must be separated by white space characters.
Problem being the white space in the class name? I've tried to put class="fancybox fancybox.iframe" in ID, svg and style, and it doesn't work. Ran out of ideas.

**Comment by fancyapps** [comment]
@infatum1 Sorry, I do not understand you - do you want to display SVG element directly or from some PHP page?

If you want to use iframe, then simply add `data-type="iframe"` to your link, example:

```HTML
<a data-fancybox data-type="iframe" data-iframe='{"preload":false}' href="http://chemistrytable.scienceontheweb.net/index_eng_svg.php">
    Click me
</a>
```

Alternatively, display as inline content - https://codepen.io/anon/pen/rYdjWj?editors=1010 or as image - https://codepen.io/anon/pen/QOmdgb?editors=1010

**Comment by infatum1** [comment]
@fancyapps 
1. data-type="iframe" creates an iframe, but it cuts it. [Link to screenshots for preload="true" and preload="false". ](https://photos.app.goo.gl/KesLKTcfm45u8HHp2)
2. inline content does [this](https://photos.app.goo.gl/46fn7Ow0ZEhUCbug2)
3. It can't be done with one image. I'm having one SVG image divided in sections (rect). Every rect is wrapped around unique <a href> </a>, which should display a web page in an iframe, making the rest backgound grey. 

Stuff I'm trying to achieve is already made [here](http://chemistrytable.scienceontheweb.net/). It's just that this time I want to build it with SVG, whereas a user could infinitely zoom without sacrificing for image quality. Thanks for replying.

**Comment by fancyapps** [comment]
Actually, I misunderstood your comment, because it was not related to this thread. 

So, you do not need to have `<a>` elements, you can make any element clickable, for example, 

`<rect class="fancybox fancybox.iframe" href="elements/H.php" x="48.9" y="84.3" class="st0" width="96.3" height="96.3"/>`

or using v3:

`<rect data-fancybox data-type="iframe" data-src="elements/H.php" x="48.9" y="84.3" class="st0" width="96.3" height="96.3"/>`

**Comment by infatum1** [comment]
1. Looks like [this.](https://photos.app.goo.gl/oVoj96iDjxzHELeh1)

2. Version 3 like [this. ](https://photos.app.goo.gl/T5FQzPMRyupvvOa22)

**Comment by infatum1** [comment]
Have both, earlier and newer version of fancybox. [Website link.](http://chemistrytable.scienceontheweb.net/index_eng_svg.php)

Website [source code.](view-source:http://chemistrytable.scienceontheweb.net/index_eng_svg.php)

Applied `<rect class="fancybox fancybox.iframe" href="elements/H.php" x="48.9" y="84.3" class="st0" width="96.3" height="96.3"/>` to H element

and `<rect data-fancybox data-type="iframe" href="elements/Li.php" x="47.6" y="184.5" class="st2" width="96.3" height="96.3"/>` to Li element.

**Comment by fancyapps** [comment]
You forgot `rel="stylesheet"` and therefore CSS is not loaded. Also, it is not good idea to use both versions on the same page.

**Comment by infatum1** [comment]
My bad. Copied from a solution provided on [stackoverflow.](https://stackoverflow.com/questions/47393640/assign-multiple-classes-to-separate-svg-elements). Was raising the question there first.

I keep the earlier version for redundancy. Just in case. Now, I have taken it out and left version 3 and still the iframe [looks shrunk.](https://photos.app.goo.gl/iOnhG84QTY3OUayq1)

**Comment by fancyapps** [comment]
Your iframed page is actually 16px height. You can easily see this using developer tools. This is because the only element having content (and height) is positioned absolutely. 

So, you can ether override the height by using something like this:

```CSS
.fancybox-slide--iframe .fancybox-content {
    height: 1000px !important;
}
```

or by removing `position: absolute;` from `#apDiv1` element.

**Comment by fancyapps** [comment]
Anyway, you could have solved most of your issues just by learning how to debug your page. If you did not know, you can right-click on element and choose Inspect or Inspect element. 

So, for example, you posted multiple times about "Looks like this" issues, but it took me 2sec to see that none of the fancyBox elements had any CSS rules, so, obviously, CSS file was not loaded. 

Also, I have no idea why "H element has changed its background color from purple to black", because I do not see any CSS rule or svg property for this element related to the color.

**Comment by infatum1** [comment]
No need to teach me about debug. Thanks. Doing a project for free after a 12 hour work day is less easy...

Despite having removed the apdiv1, the issue goes on...
Still wonder how it happens to work on pages where the same Apdiv1 is having width: 387px; height: 376px; Probably because APdiv1 is then again picked up in individual pages, which are clicked. It has  height: 19000px;

I've tried to change the CSS to the following and still no luck:
.fancybox-slide--iframe .fancybox-content {
  padding: 0;
  width: 80%;
  height: 190000px !important
  max-width: calc(100% - 100px);
  max-height: calc(100% - 88px);
  overflow: visible;
  background: #fff; }

Pressing on [Li element.](http://chemistrytable.scienceontheweb.net/index_eng_svg.php) yields shrunk page.

**Comment by fancyapps** [comment]
I'm glad you sorted that out. 

Anyway, this was a big off-topic, but, returning to the discussion about SVG support, you can simply use `data-width` and `data-height` attributes to set optimal image size, example:

```HTML
<a data-fancybox="svg" data-width="500" data-height="500" href="https://image.flaticon.com/icons/svg/51/51767.svg">
    <img src="https://image.flaticon.com/icons/svg/51/51767.svg" />
  </a>
```

Demo - https://codepen.io/anon/pen/QOVjdx?editors=1100
