### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by iBars** [fancyapps/fancybox#1525]
I have JS error about "maximum call stack size exceeded" when I click here (see attached images below) on [my site](http://doma-nk.ru). It causes input fields inside fancybox unavailable for write, just first field appears always focusable, so our potential customers can't request feedback, which is extremely important.

![1](https://user-images.githubusercontent.com/3519015/28139308-7d033ed0-675c-11e7-97ca-6c75da53a5d6.png)
![2](https://user-images.githubusercontent.com/3519015/28139307-7d031af4-675c-11e7-8a54-0928cbe29a60.png)

**Comment by fancyapps** [comment]
Hi,

Looks like something is trying to prevent fancyBox from auto-focus, but fancyBox keeps trying to focus on self, resulting in that error message.

You are mixing two modals - bootstrap and fancyBox and I guess that bootstrap does not want to loose focus.

Possible solutions:
1) Avoid mixing different modal scripts. You can switch to fancyBox only, because fancyBox can open multiple modals at the same time.
2) Upgrade fancyBox to v3.1, there are some improvements to make it play nicer with others.
3) Stop focus traping on bootstrap (or set `autoFocus:false, trapFocus:false` if using fancyBox v3.1)

**Comment by iBars** [comment]
Fixed by removing tabindex="-1" for Bootstrap modals. Thank you
