### ISSUE TITLE
Fancybox commercial restriction incompatible with the GPL v3

### ISSUE THREAD

**Issue by dionrhys** [fancyapps/fancybox#1533]
_(Disclaimer: I am not a lawyer)_

The fancyBox licence page [on the website](http://fancyapps.com/fancybox/3/#license) and in the [GitHub readme](https://github.com/fancyapps/fancybox#license) state that:

> fancyBox is licensed under the GPLv3 license for all open source applications.
> A commercial license is required for all commercial applications (including sites, themes and apps you plan to sell).

The restriction on commercial applications here is incompatible with the GPL v3 licence and it's covered in its FAQ:

> **I'd like to license my code under the GPL, but I'd also like to make it clear that it can't be used for military and/or commercial uses. Can I do this? ([#NoMilitary](https://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary))**
>
> No, because those two goals contradict each other. The GNU GPL is designed specifically to prevent the addition of further restrictions. GPLv3 allows a very limited set of them, in section 7, but any other added restriction can be removed by the user.

The GPL v3 FAQ also explicitly notes that GPL software may be modified, redistributed and sold commercially by others (in adherence with the licence terms):

> **If I use a piece of software that has been obtained under the GNU GPL, am I allowed to modify the original code into a new program, then distribute and sell that new program commercially? ([#GPLCommercially](https://www.gnu.org/licenses/gpl-faq.en.html#GPLCommercially))**
> 
> You are allowed to sell copies of the modified program commercially, but only under the terms of the GNU GPL. Thus, for instance, you must make the source code available to the users of the program as described in the GPL, and they must be allowed to redistribute and modify it as described in the GPL.
> 
> These requirements are the condition for including the GPL-covered code you received in a program of your own.

Since this software has been released under the GNU GPL v3, there can't be any requirement to purchase a commercial licence to make use of it in a commercial setting. Enforcing this would be a violation of the licence terms.

Now I'm not the person to provide a solution to this - it's your project! But maybe changing the text of the licence statement from "requiring" a commercial licence to "recommending" one instead would be the easiest way forward. The code is under GPL v3, so the "commercial licence" being offered right now for fancyBox is in fact just a promise to offer enhanced support for the software and a commitment to keep working on the project.

For what it's worth, I really like how fancyBox looks and works. I just wanted to highlight this in case you find a commercial use of fancyBox that didn't have a "commercial licence". This is explicitly allowed by the GNU GPL v3.

**Comment by fancyapps** [comment]
Hi,

Thanks for your thoughts. Since this dual licensing creates more questions and confusion than brings any gain, licensing under GPL will be dropped.

**Comment by mudrd8mz** [comment]
Hello. So what's the status of this? The page https://fancyapps.com/fancybox/3/ still claims that dual licensing statement which I agree is not compatible with GPL. Thanks in advance for the clarification.

**Comment by howdev** [comment]
If software is under GPL3 you don't pay for commercial use, because that is just opposite of GPL. Doesn't seem like Fancybox want to be  offered for free. so, well. I guess we have to look for an alternative gallery.

**Comment by fancyapps** [comment]
It always surprises me when I say - oh, here is a software I have been working on for more than a year, you can use it for a small fee, it will save your time, etc; and the response is - nah, I want it for free.

**Comment by danmarsden** [comment]
Hey! - thanks for following up - I should clarify - @mudrd8mz posted here because we (Moodle) had a plugin submitted for review which included your code - (Moodle uses GPLv3) - It makes complete sense to that you would like a fee if someone wants to use it in a commercial environment - we have no objections or concerns over this! We had to reject the Moodle plugin submission because your licensing statement wasn't compatible with the GPL and therefore the code could not be distributed in a Moodle plugin.

Ideally it would just be good for you to completely remove the reference to GPL in your licensing statement to avoid confusion by people who "think" your code is licensed under GPL when it is not.

Thanks for sharing your code!

**Comment by siegerg** [comment]
Hey,

I have a licensing question, that is not covered by the above comments:

We want to use fancybox in a module, that we are going to sell to numerous customers. We therefore would choose the extended commercial license.

Could you please clarify that with the commercial license the GPL does not apply to our use.
If I understood it correctly, you are using a dual-licensing-model where you use GPL for OS-projects and the commercial license for other purposes. It's just a little confusing to me, because the other comments interpreted your dual licensing as an addendum to the GPL (which I agree would be in incompatible with GPL).

Thanks for a clarifying comment. If it's clear to us, that the GPL does not apply, just the commercial license, we would be happy to include fancybox in our module (because our licensing is also incompatible with the GPL).

**Comment by Istador** [comment]
@siegerg

If you purchased the commercial license, and it allows you to do the things that you want, then you're fine (I don't know the contents of the commercial license and what rights it grants you).

If a software is available under multiple licenses, then the license you have is in no way restricted, limited or influenced by other licenses. Given that you purchased the license from the actual author / copyright holder of the software, who is allowed to sell these rights to you.

On the other hand, if another license grants you more rights than the one you have, you can use both to benefit from them both, as long as you comply to all requirements stated in both licenses. (You should carefully read both licenses in this case for exceptions and verify that they both apply to the same version of the software. Commercial licenses sometimes only apply to specific commercial versions of software, meaning that public licenses can't be used for commercial versions, and commercial licenses can't be used for public versions - unless stated otherwise.)

---

The point of this issue is that the GPLv3 grants the right to commercially use, modify, redistribute and sell this software as long as the requirements and restrictions of the GPL are followed (e.g. copyleft). Any restrictions of these rights aren't allowed according to the GPL license.

The GPLv3 contains the following:
> If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.
> [...]
> Additional terms, permissive or non-permissive, may be stated in the form of a separately written license, or stated as exceptions;
> the above requirements apply either way.

And this basically allows any company to ignore the additional restriction and use the software commercially.

---

@fancyapps

If you want to restict free/unpaid commercial use of the software, then don't distribute it under GPL. Period.

One approch could be to use another license for new versions of the software, which restricts commercial use. Old versions of the software that were distributed with the GPL could still be used for commercial use (you can't restrict that retrospectively), but if a user wanted to use newer versions of the software they'd have to comply to the new license.

The problem with this approach would be, that this project has more than one contributor. The contributions made by that other people were all made under the assumtion that it is available under GPL and one additional commercial license. They'd need to aggree that new versions of the software, that continue to use their contributions, can be distributed without the GPL.

If you'd want to make a change like this, be open about it and don't do it silently. People might use your software by using `npm`. Updating this software to a new version, by updating their dependencies (or installing it without using a lockfile) might change the license without them noticing. You should either:
- release the software with the new license under a new name (e.g. `@fancyapps/fancybox4`) so that users have to change their dependencies manually,
- or make a change to the project that breaks existing software and release it under a new major version number 4.0.0.

Puting a script into the install process that notices about the change and requires user interaction to confirm it might sound like an alternative option, but `npm` might be used with `--ignore-scripts` in an automated process.

---

Please don't misinterpret this issue or the comments here as people wanting things for free or profit from your work. It is a legal issue that your project currently has. It's confusing to possible users and doesn't work the way you want it to.

I personaly don't think you're selfish or anything for wanting money for your work. I also have no personal interest in using your software for anything. I do support open source organizations and projects that I use, if possible, by personally donating money and/or by submitting issues and pull requests (in my non-work time).

I learned a while ago that the company I work for is using your software and has purchased a commercial license for it. That's totally fine and a good thing. But today a colleague of mine (other department) mentioned to me that this is open source software and that they had to purchase it to be allowed to use it commercially. This pick my interest because it's contradicting with most open source licenses that I know of. And because I recommended a few time that we as a company should donate financially to all the open source projects that we use. I even asked several times for permission to submit the code that we developed to improve and adapt open source back to the projects - without getting a reply by my superior.

**Comment by mudrd8mz** [comment]
Excellent summary, many thanks @Istador
