### ISSUE TITLE
Prevent Activation if dragged (not a real mouse click)

### ISSUE THREAD

**Issue by iTayGNR** [fancyapps/fancybox#1539]
I'm using Fancybox with [LightSlider](https://github.com/sachinchoolur/lightslider), and when I drag the carousel with the mouse above the picture and then release the mouse, Fancybox gets activated. Of course it was not a real click and because of that I can't see a reason for why would it trigger.

I've seen [this solution on Stack Overflow](https://stackoverflow.com/questions/15815658/fancybox-to-not-activate-if-dragged) but it's not optimal since when I call `$.fancybox.close();`, I see Fancybox comes in and then out (the fade effect is visible for no reason).

Is there any solution for it?

[Demonstration on Codepen](https://codepen.io/anon/pen/wqweGz)

**Comment by fancyapps** [comment]
Hi,

This issue rises if you initialize fancyBox directly and then slider can not cancel click event that triggers fancyBox. 

To overcome this, you have to initialise fancyBox using "selector" option (available since fancyBox v3.1). Then event delegation will be used and sliders will be able to cancel event bubbling. 

Example:

```JS
$().fancybox({
  selector : '[data-fancybox="images"]',
  animationEffect : "fade"
});  
```  

See these demos
- using Swiper - https://codepen.io/fancyapps/pen/eWVyVg 
- using Slick - https://codepen.io/fancyapps/pen/gWvorB

It should be similar to any slider slider.

**Comment by iTayGNR** [comment]
I tried your solution but I can't see any difference.
More that that, the demos act the same if you initialize fancyBox with `selector` or with the jquery selector.

**Comment by fancyapps** [comment]
Looks like slider script just does not play nicely with others, it should cancel click event (like others do) when releasing after dragging. I would suggest to look at alternatives.
