### ISSUE TITLE
Q: Where i can find the code for "Morphing modal overlay" ?

### ISSUE THREAD

**Issue by Siton-Systems** [fancyapps/fancybox#1541]
And all other "examples under **Advanced**" (looks great)? (codepen maybe or somewhere in the docs).

**Comment by mjcampagna** [comment]
It's all in the page source.

**Comment by fancyapps** [comment]
Hi,

You can find collection of demos here - https://codepen.io/fancyapps/pens/public/

Here is "Morphing modal overlay" demo - https://codepen.io/fancyapps/pen/rmwyXN
While the effect might look simple, the code is not so, because there are multiple sequential animations and they need some calculations.

**Comment by Siton-Systems** [comment]
Thanks a lot!

**Comment by Irina0302** [comment]
Thanks a lot!)))very cool
