### ISSUE TITLE
Module not found: Error: Can't resolve 'jquery-fancybox'

### ISSUE THREAD

**Issue by IsmaelEzequiel** [fancyapps/fancybox#1583]
Hey, guys. What's up?

I'm trying to import fancybox using es6 syntax ( import 'jquery-fancybox' ) but I'm getting this error below, could one help me?

My environment: Vagrant, webpacker, rails, yarn. 

I'm using: ```npm install @fancyapps/fancybox --save```
the lasted version.

```
import 'jquery-fancybox';

ERROR in ./app/javascript/packs/application.js - Module not found: Error: Can't resolve 'jquery-fancybox' in '/vagrant/app/javascript/packs'
```

PS: Any other module I can import normally.

**Comment by RomkaLTU** [comment]
Should be:

`import '@fancyapps/fancybox'; `

This didn't work too, brings error:

`Uncaught TypeError: t is not a function`

**Comment by IsmaelEzequiel** [comment]
Yeah, I solved my problem importing like that:

`import @fancyapps/fancybox;`
or
`import fancybox from @fancyapps/fancybox;`

**Comment by joaoeaugusto** [comment]
I've got the same error as @RomkaLTU `Uncaught TypeError: t is not a function` even using @IsmaelEzequiel import solutions on his previous comment. Webpack doesn't like those import due to the missing quote signs though...

jQuery is globally exposed on my project, but Fancybox can't load it for some reason. I've got other libraries working fine with jQuery.
Any idea what could be? By the way, what version of Fancybox are you guys using?
I'm running Fancybox 3.1.20, jQuery 3.2 and Webpack 3.5.5

**Comment by fancyapps** [comment]
Maybe it is because fancyBox expects the reference to jQuery here - `window.jQuery`

**Comment by joaoeaugusto** [comment]
Ha! Nice one. I just had to add the `"window.jQuery":"jquery"` to `webpack.ProvidePlugin` in my `webpack.config.js`, so:
```
new webpack.ProvidePlugin({
   $: 'jquery',
   jQuery: 'jquery',
   "window.jQuery": "jquery"
})
```

**Comment by srkela** [comment]
Hi,
I have similar error
`TypeError: t.instance.$refs is undefined`

I am using webpack and jQuery is declared as global variable. 
```
		new plugin.webpack.ProvidePlugin({
			$      			: 'jquery',
			jQuery			: 'jquery',
			'window.jQuery'	: 'jquery'
		}),
```
Other jQuery plugins work well

Only way I can make it works is to wrap fancybox code in in $(document).ready() in common.js file. but that solution doesn't work for me.

**Comment by CecileV** [comment]
Hi,

I use it and it's works : 

``
// Fancybox
require('@fancyapps/fancybox');
``
