### ISSUE TITLE
General issue integrating fancybox

### ISSUE THREAD

**Issue by OnionTerror** [fancyapps/fancybox#1589]
Heya folks, Im pretty new to javascript and CSS, but my boss has asked me to come up with a new website design for him while he is away, and i wanted to integrate fancy box as a nice gallery.
as far as I can tell, its all working, but the gallery itself appears below all the other sections right at the top of the page. I do believe this one is beyond me! Can you fellas possibly tell me whats wrong? Ive attached the best image i can, you can just about see the gallery underneath the train picture.
Thanks very much guys!
![web](https://user-images.githubusercontent.com/31238562/29556493-4f4d7f98-8726-11e7-93f3-5b19348989d3.png)

**Comment by fancyapps** [comment]
Hi,

Since you have not provided a link to your page (looks like you are working locally), I can only try to guess. Have you checked z-index values for these blocks?
Maybe you could upload your page somewhere so it can be inspected. If you wish, you can send  link privately using twitter or gitter.im

**Comment by OnionTerror** [comment]
Heya Janis, Thanks for your prompt reply, I tried to use a RAR but as i
expected the thread wouldnt allow me to attach it, and I understand that
just a picture is difficult to diagnose. Ive been through the Z indexes,
and as far as I can tell they are in order, with the seperate sections
having z indexes of 1-5 and the fancy app being in the region of 99999. Is
there a way I can send you the project file as I dont have access to a
server right now.
Sorry for the inconvienience, and thankyou very much for your help!
Richard

**Comment by fancyapps** [comment]
Well, you can contact me via email info at fancyapps dotcom.

**Comment by fancyapps** [comment]
So I fixed your page by making these changes:

- You included fancyBox JS file, but you included another jQuery instance afterwards making fancyBox to disappear;
- You forgot to add `rel="stylesheet"` to CSS link;
- I added `data-type="image"` to links linke `http://unsplash.it/400/266?random=11`, because they were not recognized by fancyBox as images;
- Added `compensate-for-scrollbar` to `#topnav` element to fix jumping when opening/closing fancyBox.

**Comment by OnionTerror** [comment]
Thanks Janis, thats some valuable information. Programing still confuses me
quite a bit, im a lowly engineer really.
Thankyou very much for your assistance again.
Ill most likely be buying a licence for your product soon.
Regards
Richard
