### ISSUE TITLE
Close button not showing in facebook app. browser

### ISSUE THREAD

**Issue by rinabh** [fancyapps/fancybox#1591]
I have used fancyBox v3.1.20 & found issue related to close button.
It doesn't showing close button in iOS devices, when open in facebook app. browser.

Working proper in android device.

![ios_close](https://user-images.githubusercontent.com/15263290/29700524-c287a422-8954-11e7-8f99-69cf9356e0b7.PNG)

**Comment by fancyapps** [comment]
Hi,

Well, the problem is that browser creates page higher than the visible area, therefore you need to scroll up to see buttons. 

I am not sure that this can be properly _fixed_ as workarounds can create other issues (https://stackoverflow.com/questions/35421247/wrong-viewport-page-height-in-embedded-facebook-browser-in-ios-9-x).

If you are really concerned about this issue (user can still close gallery using touch gestures), then I suggest to detect FB browser and apply some some CSS class that pushes toolbar down a bit so it would be always visible. Or maybe reposition it by default.
