### ISSUE TITLE
Apache 2 License incompatility

### ISSUE THREAD

**Issue by sebastian-raubach** [fancyapps/fancybox#1619]
I'm working on an open source project that is licensed under Apache License v2.0.
I'm aware that fancybox's license for open source projects is GPLv3 and I only recently found out that the two are not bidirectionally compatible which means I cannot include fancybox in our software (assuming I understood that correctly).

Just out of interest: are you considering moving to a different license in the future?
If not, I might have to stop using fancybox which would be a shame, because it's such a great tool.

**Comment by fancyapps** [comment]
Hi,

I would love to change licensing to MIT or Apache License, but, since I do not have sponsors/patreons, I make living by selling commercial licenses. I chose GPL license, because it is more restrictive. Apache license gives huge leeway to anyone who wants to use the Apache license codes in their products - they can cherry pick what they want from the code, make their own improvements/changes over it and then release it as their product. And that is not what I would be happy about.

btw, could you tell the name of the project or is it a secret project? 😄

**Comment by sebastian-raubach** [comment]
I completely understand and respect your position here. I'm just trying to figure out where that puts our project.
We develop a framework that other people can use to make their plant data available.
So, we can't use fancybox under the open source license without changing our software to GPLv3. Would it be possible to purchase an extended license and include that with our software under Apache license v2?

**Comment by fancyapps** [comment]
It would be best to make fancyBox optional as a plugin/module with a note about licensing.

**Comment by sebastian-raubach** [comment]
I'm afraid that's not an option. Looks like I'll unfortunately have to look for an alternative.

All the best for your project though! I really liked it
