### ISSUE TITLE
How to get the parent DIV and ID of the current Image in FancyBox by clicking the Button

### ISSUE THREAD

**Issue by Sathiyamm** [fancyapps/fancybox#1627]
How to get the Parent DIV and the image ID of the current image on clicking the button in FANCYBOX Plugin.

**Comment by fancyapps** [comment]
Hi,

First, you need to get reference to the fancyBox instance (fancyBox v3 supports multiple instances) and current slide object. You either receive them as parameters when using callbacks or you can use this shortcut - `$.fancybox.getInstance().current`. Each slide object has `$content` variable that is reference to the content, for example:

`$.fancybox.getInstance().current.$content`

For images, this would be parent element of the image. For your convenience, there is also a reference to the image:

 `$.fancybox.getInstance().current.$image`

**Comment by Sathiyamm** [comment]
Please, I need the backend Id of the li of the current image which is displayed in overlay.

**Comment by fancyapps** [comment]
Well, I have no idea what that image is and where did it come from. Is this the original ling containing the thumbnail you clicked to open the fancyBox? Then you can access original link like this:

`$.fancybox.getInstance().current.opts.$orig` 

It is under opt(ion)s, because it can be set set/changed using options. And image would be found like this:

`$.fancybox.getInstance().current.opts.$orig.find('img')`

**Comment by Sathiyamm** [comment]
This is My Working code in my scenario :+1:  $.fancybox.getInstance().current.opts.$orig.find('img').parent();
Thanks for your help.
