### ISSUE TITLE
Q: srcSet: data-width /data-height - perfoamance?

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [fancyapps/fancybox#1633]
For example image 1920x1080.

From **speed** aspect its better to use data-width/data-height (Yes/No)? I dont 100% understnad the docs about this topic.
```
data-width="1920"
data-height="1080"
```
On this example 
https://codepen.io/fancyapps/pen/YQKKYx?editors=1000
I must use data-width for the srcSet to work well?

**Comment by fancyapps** [comment]
Hi,

These attributes are necessary to immediately display image after user clicks the thumbnail. Thumbnail image is viewed while real image is still loading. This should make users more happy, because they see something happening instead of just staring at the loading icon.

So, without using these attributes, the flow goes like this:

user clicks thumbnail -> 1) real image starts loading; 2) loading icon is displayed; -> real image loads, the script get width/height, makes calculations and puts it in the place;

but, if you provide thumbnail and dimensions of the real image:

user clicks thumbnail -> 1) real image starts loading; 2) script makes calculations and displays thumbnail image immediately; loading icon is displayed only if real image is not loaded after some delay; -> real image loads and is put in the place;

**Comment by Ezra-Siton-UIX** [comment]
Thanks!
