### ISSUE TITLE
Problems with the back button

### ISSUE THREAD

**Issue by kofiowusu1** [fancyapps/fancybox#1669]
First off, thank you for this awesome Software! I wasted too much time customizing swipebox until I found Fancybox.

There are two bugs with the back button on mobile devices.

Bug1:
1. Start on Google
2. Go to fancyapps
3. Open an Image in the showcase
4. Swipe to next image
5. Close by using 'x'
6. Use the back button

Now the back button does _nothing_. It does not go back to the previous website.

Bug2:
This bug is more annoying.
1. Start on Google
2. Go to https://codepen.io/fancyapps/pen/gWvorB?editors=1010
3. Open an Image
4. Press back button

I expected that Fancybox closes, but you leave the whole website and land on Google.

PS: Browser is Chrome on Android.

It would be nice if you fix these bugs, at least I need some workaround for Bug2 currently.

Thank you!

**Comment by fancyapps** [comment]
Hi,

Since it is not possible to handle "back button click", the only workaround is to manipulate with history entries. Unfortunately, is not possible to make it work perfectly, because, for example, you can add new history entry, but you can not remove.

About 2nd example - this is because you have opened iframed page. 

So, you either disable hash module (set `hash: false`) or you can try to tweak it.
