### ISSUE TITLE
Small button does not appear in Fancybox 3.2.0

### ISSUE THREAD

**Issue by maartenmachiels** [fancyapps/fancybox#1719]
Hi,

I was investigating this question posted on StackOverflow regarding the small close button not appearing in the top right on modals.
https://stackoverflow.com/questions/45366375/fancybox-3-how-to-show-the-small-close-button-for-modal-iframe

In the example on Codepen, the close buttons do appear:
https://codepen.io/fancyapps/pen/OOXxLa

But when tested out in the wild, nothing seems to happen.
Even when using the options attribute, nothing happens:

`data-options="{'smallBtn': true}"`

The stackoverflow user mentions the same thing when initializing Fancybox via JavaScript.
What am I doing wrong?

**Comment by fancyapps** [comment]
Hi,

1) That SO question is complete nonsense, if you set `modal:true`, then no buttons are displayed. 

2) On the other hand, it turns out that it really does not work when set using inline option, but works fine when setting options while initializing - https://codepen.io/anon/pen/jaVyYV?editors=1010

**Comment by maartenmachiels** [comment]
Hi,

Thank you for your answer. I did manage to get the button working in the examples you provided. A small snag still remains though, when using a form as inline content.

https://codepen.io/speshdiv/pen/pdNRXW

I already found a workaround by wrapping the form in a div, then it works:

https://codepen.io/speshdiv/pen/ooYZxK

Not a big problem though.
