### ISSUE TITLE
Reason for Math.abs( self.distance ) > 10

### ISSUE THREAD

**Issue by W1zzardTPU** [fancyapps/fancybox#1721]
What's the reason for if ( Math.abs( self.distance ) > 10 ) { in gestures.js ?

It seems to introduce a little perceived lag when using touch

**Comment by fancyapps** [comment]
Hi,

This is needed to determine in what direction to drag.

**Comment by W1zzardTPU** [comment]
Why 10 and not just 1 ?

**Comment by fancyapps** [comment]
I remember that in early versions of v3 there were just 2 points used and the swiping on the phone was frustrating because sometimes wrong direction was calculated.  It is hard to explain the reason, it would be easier to show. You see, casually swiping on the phone, the drawing line is rarely horizontal or vertical and increasing the distance it is possible to more accurately calculate the angle.

**Comment by W1zzardTPU** [comment]
I think I get what you mean. Will do a little bit of testing.

Which device/browser are you using for testing?

**Comment by fancyapps** [comment]
There is really no difference, but I`m using an iPhone / latest Safari.
