### ISSUE TITLE
Download button needs to have own css style

### ISSUE THREAD

**Issue by Eldenroot** [fancyapps/fancybox#1727]
New download button has <a ...> tag - it means that it behave like a link - the color is changed when you visited that (open). It would be better to use button instead of "a" tag

`<a download="" data-fancybox-download="" class="fancybox-button fancybox-button--download"`

to something like

`<button data-fancybox-download="" class="fancybox-button fancybox-button--download"`

Is that possible?

**Comment by Eldenroot** [comment]
![image](https://user-images.githubusercontent.com/778890/32626102-a9cf69f8-c58e-11e7-921b-723aa31830b2.png)

**Comment by fancyapps** [comment]
Hi,

Anchor element is used here just to make things simpler, because it uses `download` attribute - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download
(sadly, not supported by IE11 - https://caniuse.com/#feat=download) 

It would, of course, be possible to use <button> element, but then it would need to have some click event handler to start download.

**Comment by fancyapps** [comment]
Hi,

Actually, that button got color from your CSS, because you used "stronger" CSS rule - `a:link`. 

Anyway, I used even "stronger" rule in the last commit, that should override this.

**Comment by Eldenroot** [comment]
Thank you!
