### ISSUE TITLE
confirmBox with Iframe

### ISSUE THREAD

**Issue by boillatlucas** [fancyapps/fancybox#1745]
Hello,
I want to make a confirmation box as in this example [(https://codepen.io/fancyapps/pen/Ebmqgv),](https://codepen.io/fancyapps/pen/Ebmqgv) I use exactly the same code except that the buttons are stored in a php file (I'll add some something else after) and so I changed the type of html to iframe and source my php file instead of the html button directly.
All are displayed and working properly except that I do not get a value in the callback, the variable 'e' is undefined.
`afterClose : function( instance, current, e ) {
      }`
Is it normal that it does not work with the iframe type or have i forgot something ?
I use the version 3.2.10
I can provide my code if necessary
Thanks

**Comment by fancyapps** [comment]
Hi,

If you want to recreate something similar using iframes, then your buttons inside iframed page should contain something like this to make it work:

`onClick="parent.jQuery.fancybox.getInstance().close(event); return false;" data-value="1"`

But, since you are using iframes, it is even easier, you can simply display iframe and then add some click handler to OK button within iframe.
