### ISSUE TITLE
cordova project IOS platform: fancybox bad centered in iframe 

### ISSUE THREAD

**Issue by andvis** [fancyapps/fancybox#1756]
Hello, I'm using fancyapp in a cordova project. The main page has an iframe and I'm opening the fancyapp inside the iframe. All works fine in Android platform. The same code doesn't works well in IOS platform. The fancyapp open vertically outside the screen. It is vertically centered on the iframe content size instead of the screen size. It is also dependent on to the scroll amount of the document.

Is there a way to fix this issue?

**Comment by fancyapps** [comment]
Hi,

I suspect this issue is caused by fancyBox trying to fix iOS bug related to input field focusing, see https://stackoverflow.com/questions/46339063/ios-11-safari-bootstrap-modal-text-area-outside-of-cursor and other similar posts about this topic.

You could try to remove that iOS hack (it is adding `position:fixed` to the body) from the source to see if that fixes your issue, and it would be interesting to know how input focusing would work for you.

**Comment by andvis** [comment]
Thank you so much. I solved my problem putting the rule "position: fixed!important;" on body beforeShow and removing the rule on beforeClose.
Now, the other issue I encountered is the image size of the slide in iPhone landscape view. The slide comes out the screen dimension in height. The width fit the screen size but the height comes out the screen. In addition, if I try to move vertically the slide to view the hidden part, the fancybox close.
I can't use "touch: false" because the application is on the mobile device and I need of the "gestures" to control the slides.
