### ISSUE TITLE
Problem on mobile keyboard

### ISSUE THREAD

**Issue by decadence** [fancyapps/fancybox#1782]
fancybox is not working right on mobile device (Android 6.0, confirmed on two different smartphones). There is demo-site (http://ramflow:4ghJQA2DqS@ramflow.dev.icewood.net/) and when you click on this link in footer fancybox window appears.
![1](https://user-images.githubusercontent.com/1434668/34219491-62d902b2-e5c2-11e7-9f24-8de157175595.png)

But you can't enter phone number because after focus in input keyboard viewport is getting small and window disappears and appears again without keyboard.

`touch: false` didn't help.

fancybox 3.

**Comment by decadence** [comment]
I can't find any autoResize / autoPosition options.
And fancybox repositions ugly with hide/show and not with transition effect.

**Comment by fancyapps** [comment]
You use CSS to control dimensions of your html content, and content is automatically centered vertically/horizontally using Inline-Block technique (https://www.smashingmagazine.com/2013/08/absolute-horizontal-vertical-centering-css/#Inline-Block), therefore there is no need for autoResize / autoPosition options like in previous versions.

If you refer to the fact that content gets hidden for a short time after changing orientation of the device (or resizing, when mobile device is detected), then this is due to the fact that mobile browsers (especially iOS11) update page dimensions only after some delay.

About original issue - I do not have an Android device right now, therefore I am not able to test it. And I am not experienced such issue with Android device, but iOS has a long history about this issue (there is a hack for iOS for the same issue).

**Comment by decadence** [comment]
> then this is due to the fact that mobile browsers (especially iOS11) update page dimensions only after some delay.
This happens on desktop Chrome too.

So we need someone with Android to confirm this issue.

**Comment by decadence** [comment]
Tested it on Android Firefox: fancybox reappears and keyboard stays visible so I was able to enter phone number.

**Comment by decadence** [comment]
It happens even if fancybox window is really small so there is definitely something wrong with fancybox + Android Chrome keyboard.

**Comment by decadence** [comment]
Seems like Chrome hides keyboard because `.fancybox-stage` has `display: none` when page resizes.
Desktop browser lost focus on input too while fancybox window blinks with `display: none` / `display: inline-block`.

**Comment by decadence** [comment]
Adding
```css
.fancybox-stage {
    display: block !important;
}
```
resolves this. It forces fancybox to stay visible and save focus on input and this makes fancybox reposition with more pretty way.
Maybe you should add some option to control this behaviour.

**Comment by schlessera** [comment]
Same issue here, work-around from @decadence worked for us as well.

+1 from me for fixing this in Fancybox itself.
