### ISSUE TITLE
Close video player when video ends 

### ISSUE THREAD

**Issue by cengelbart** [fancyapps/fancybox#1844]
Clicking on hotlink to youtube content it properly opens frame with player, but when play ends the frame stays open showing youtube's thumbnail image which may have no relation to the snippet just played so it's a bit jarring. Option to have the frame close when video ends (reaching end of video or reaching &end=) would be fabulous.

Here are 2 webpages where I am using fancybox with youtube extensively :
http://dougengelbart.org/firsts/dougs-1969-demo.html
http://dougengelbart.org/vision/engelbart-academy.html

**Comment by fancyapps** [comment]
Hi,

It is possible, but tou would need to use YouTube API for that. 

Here is older demo - https://codepen.io/fancyapps/pen/jBKowp - but, unfortunately, it does not seem to work anymore. And I have no idea why, because the API seems not be the same - https://developers.google.com/youtube/iframe_api_reference . 

Others are experiencing problems with YouTube API, too - https://productforums.google.com/forum/#!msg/chrome/xmMSf67waIk/Pylo-kkCBwAJ
