### ISSUE TITLE
data-trigger conflicts with bootstrap popover.

### ISSUE THREAD

**Issue by abixalmon** [fancyapps/fancybox#1911]
Fancybox takes over bootstrap's data-trigger on Popover and Tooltip.

**Comment by fancyapps** [comment]
Triggering fancybox and triggering popover are contradictory actions. You have to choose one of them, because triggering both of them on click event ... just does not make any sense.

Tooltip, however, works perfectly fine, because it gets triggered on hover action. Disable back focus using `backFocus` option (or simply add `data-back-focus="false"` yo your elements) to prevent triggering tooltip after closing fancybox.

**Comment by abixalmon** [comment]
No data-gallery added.
```
<a class="btn btn-lg btn-danger" role="button" data-toggle="popover" data-trigger="focus" title="" data-content="And here's some amazing content. It's very engaging. Right?" data-original-title="Dismissible popover">Dismissible popover</a>
```
When clicked it loads fancybox.
![capture](https://user-images.githubusercontent.com/1712938/38813854-ee4753b2-41b1-11e8-8ec1-c5c9ccd98536.PNG)

**Comment by fancyapps** [comment]
Hmm, but you have `data-trigger` and that is also used to trigger fancybox on other element. This is how you can disable that - 

```JS
$(document).off("click.fb-start", "[data-trigger]");
```

**Comment by ionesculiviucristian** [comment]
Maybe consider adding vendor prefixes for data attributes in the future?

**Comment by bez4pieci** [comment]
Please reopen this. `data-trigger` is used for specifying the way the Bootstrap popover appears, namely, `hover` or `click`. At least, pleaese add this potential clash issue to documentation.

**Comment by RomanMV** [comment]
The best idea would be to rename the attribute to something like this "data-fancybox-trigger"

**Comment by fancyapps** [comment]
Sorry, I forgot to notify here that `data-trigger` has been renamed to `data-fancybox-trigger` some time ago, see https://github.com/fancyapps/fancybox/releases
