### ISSUE TITLE
Autoplay video in lightbox on mobile

### ISSUE THREAD

**Issue by j1exus** [fancyapps/fancybox#1928]
Hi!

I noticed that in your demo with Videos autoplay works great for all videos on PC, but not works on mobile for videos hosted on youtube.

On my website I faced the same issue (autoplay feature for youtube does not work on mobile).

Is there any way to fix it?

**Comment by InsanityMeetsHH** [comment]
Mobile web browsers blocking autoplay from video and / or audio. Some desktop browser too. This feature is compiled into the browsers. The reason is to save data and it is annoying. Sometimes you can simulate a click / tap on play with javascript but often browsers blocking this, too. They accept just a human made gesture.

**Comment by j1exus** [comment]
Thanks for a response!

But why e.g. lightbox with Vimeo works on mobile and youtube not?

**Comment by fancyapps** [comment]
fancybox creates HTML elements, but the rest is up to the device/browser. And YouTube/Vimeo videos are embedded using iframes, so it depends on their code, too.

Maybe it is possible to start video using YouTube API - https://stackoverflow.com/questions/17228858/how-do-videos-autoplay-on-ios-at-youtube-com but I have not tried that.
