### ISSUE TITLE
Fancybox v3.3.5 don't show thumbs-icon

### ISSUE THREAD

**Issue by DMHas** [fancyapps/fancybox#1932]
Hello,

I updated from the fancybox v3.2.10 to v3.3.5. Now missing the thumbs-icon in my galleries. I replace the new version with older and all works fine. So I guess something was changing with the newer versions.
I used the untouched versions of _jquery.fancybox.min_ & _jquery.fancybox.min_.
(example for the newer version with missing thumbs-icon: https://www.dmhas.de/australien.html#aust1-1)

Best Regards,
DMHas

**Comment by fancyapps** [comment]
Hi,

Simply create thumbnails for your links. You could use `data-thumb` attribute, too (see 3rd example here - https://codepen.io/fancyapps/pen/VyLOJX?editors=1000 ).

If I remember correctly, real image was used as as fallback for thumbnail image if it could not be found. But that was not good idea, because multiple full size images would start loading simultaneously (not great for brandwidth and pc memory).

**Comment by DMHas** [comment]
Thanks for your reply (and for the thumbnail fallback tip)!
