### ISSUE TITLE
Fancybox 3 - Show caption on image

### ISSUE THREAD

**Issue by pat-rickster** [fancyapps/fancybox#1988]
Thanks for the great lightbox, love it! :) But I'm missing the possibility to show the caption directly on the image. Or am I wrong and it's already possible?

**Comment by fancyapps** [comment]
Hi,

While I understand why you are asking for this feature, it is not so simple, because the script should consider all possible scenarios, for example - what if image is quite small and the caption contains very long text, how it would work?

And I think there somewhere already a feature request for that.
