### ISSUE TITLE
iframe scrolling on iOS device

### ISSUE THREAD

**Issue by nicjohnson** [fancyapps/fancybox#2]
When I try the iframe example at http://fancyapps.com/fancybox/#examples on an iPad, I can't get the content to scroll (using one, two, or more fingers). Do you know why this is?

**Comment by ToonSpin** [comment]
As a heads up, [the above comment](https://github.com/fancyapps/fancyBox/issues/2#issuecomment-5997068) fixed this issue for me a while ago, but this morning I found that it had cropped up again on at least iOS 7 in Chrome.

Turns out the `overflow: auto;` in the wrapper div was the key. The `overflow` wasn't doing its job properly because all of the div's children had `position:absolute`.

In the end, what solved this for me was adding `position: relative` to the div's `style` attribute, so the source of the example a-file.html becomes:

    <html>
    <body>
    <div id="wrapper" style="width: 100%; height: 100%; overflow: auto; position: relative; -webkit-overflow-scrolling: touch;">
    ...
    </div>
    </body>
    </html>

Hopefully this can help others with the same problem I had this morning. Thanks @rossb and @csdco for your trouble!

**Comment by lwen3** [comment]
This bug stills on IOS 12.1
But there is an option on iPhone that you can disable the issue:
On iPhone's settings:
- Click Safari;
- Go to Advanced (last option of the page);
- Go to Experimental Features (last option);
- Enable Async Frame Scrolling (default is disabled);

I problem solved whith this option enabled.
