### ISSUE TITLE
CSS validation issues

### ISSUE THREAD

**Issue by XhmikosR** [fancyapps/fancybox#2005]
@fancyapps: while scanning a project of mine that's using fancybox I noticed these 3 errors:

```
351 | .fancybox-button svg path | only 0 can be a unit. You must put a unit after your number : 3
-- | -- | --
369 | .fancybox-button--share svg path | only 0 can be a unit. You must put a unit after your number : 1
425 | .fancybox-close-small svg | only 0 can be a unit. You must put a unit after your number : 1.5
```

Can you tackle those an make a new patch release?

Thanks!

**Comment by sideshowbarker** [comment]
>  3,1,1.5 - is a VALID way to define the "stroke-width" of svg paths (the thickness of svg lines) in a "unitless" way.

No it’s not — not according the CSS specification for `stroke-width`. The units are required.

See https://drafts.fxtf.org/fill-stroke/#stroke-width, or if you prefer, https://www.w3.org/TR/fill-stroke-3/#stroke-width — they say the same thing:

> Value: `<length-percentage>#`

…where `<length-percentage>#` is a link to:

https://drafts.csswg.org/css-values-4/#typedef-length-percentage

> `<length-percentage>`
>
> Equivalent to `[ <length> | <percentage> ]`, where the `<percentage>` will resolve to a `<length>`

…where `<length>` is a link to:

https://drafts.csswg.org/css-values-4/#length-value

> Lengths refer to distance measurements and are denoted by `<length>` in the property definitions. A length is a dimension.

…where *dimension* is a link to:

https://drafts.csswg.org/css-values-4/#dimension

> The general term _dimension_ refers to **a number with a unit attached to it**; and is denoted by `<dimension>`.

>  https://css-tricks.com/almanac/properties/s/stroke-width/

Yeah the information on that page is wrong; it doesn’t conform to the current requirements in the relevant CSS spec. As outlined above, the relevant CSS spec says the value must be a CSS _length_, and a CSS *length* must have a unit. For further confirmation of that, see:

https://developer.mozilla.org/en-US/docs/Web/CSS/length

> The `<length>` data type consists of a `<number>` followed by one of the units listed below. As with all CSS dimensions, there is no space between the unit literal and the number. The length unit is optional after the number `0`.

And for the cases of non-conforming `stroke-width` values in `jquery.fancybox.min.css`, the W3C HTML checker correctly reports errors:

https://validator.w3.org/nu/?doc=https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.css

> Error: `stroke-width`: only `0` can be a unit. You must put a unit after your number.

**Comment by sun4all** [comment]
My current insights: You are probably right, the svg-draft I refered to, is very old (2011), and maybe already deprecated??? 
https://www.w3.org/TR/SVG11/coords.html#Units
7.10 Units: All coordinates and lengths in SVG can be specified with or without a unit identifier. When a coordinate or length value is a number without a unit identifier (e.g., "25"), then the given coordinate or length is assumed to be in user units (i.e., a value in the current user coordinate system). For example:<text font-size="50">Text size is 50 user units</text>
Example from the same document: 
`<rect x="0" y="750" width="375" height="187.5" stroke-width="37.5"/>` 
BTW: What is the last normative directive for svg stroke-width, today in 2018? 
The 2017 draft, you refer to, says ... This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress ... 
Best Regards, sun4all

**Comment by sideshowbarker** [comment]
> the svg-draft I refered to, is very old (2011), and maybe already deprecated???
https://www.w3.org/TR/SVG11/coords.html#Units

Yes, that document is very out of date and no longer being updated.

In general, you pretty much never want to use any documents under https://www.w3.org/TR. They are almost always out of date as soon as they’re published. So they often don’t contain important bug fixes and corrections and refinements.

Instead you always want to find the latest editor’s draft and use that instead. The reason you want to do that is because that’s what browser implementors work from — that is, browser implementors never use the https://www.w3.org/TR versions. Instead they work for the editor’s drafts because those drafts are continuously maintained and have the latest bug fixes and corrections and refinements.

> BTW: What is the last normative directive for svg stroke-width, today in 2018?

https://svgwg.org/svg2-draft/painting.html#StrokeWidth

> The 2017 draft, you refer to, says ... This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress ...
 
Yeah, that’s just a boilerplate disclaimer. Regardless of any disclaimers, as I said, you want to always find and use whatever version is the latest one the editor is actively maintaining and keeping up to date. Otherwise you’re using an outdated version that very likely has spec bugs.

**Comment by sideshowbarker** [comment]
> the document furthermore tells basically what to do, if unitless values are found

Right. But that information is for browser implementors, not for authors. The way specs for web technologies are written these days, the include two separate things: (1) the specs state requirements for what is valid — what authors must use in their documents, and (2) the specs state requirements for what browsers must do for cases of invalid input — when authors violate the requirements and produce invalid documents.

In other words, the specs contain browser requirements for processing both valid and invalid input.

> nowhere is stated that it is wrong to use "user units" in 2018 like stroke-width: 999, or basic unitless svg values like viewBox="0 0 4000 2000"

It’s stated unambiguously at the place I cited and which you also indicated you’ve read:

https://svgwg.org/svg2-draft/painting.html#StrokeWidth

That says the `stroke-width` value must a `<length-percentage>`. Look back at https://github.com/fancyapps/fancybox/issues/2005#issuecomment-405057281 for detailed explanation of why that indicates the units are required.

Which part of the explanation is unclear or ambiguous.

> Sorry, in my opinion, after reading this, the w3c validator is simply wrong

Sorry, but the validator is definitely not wrong here. It conforms to the requirements in the CSS spec, as I’ve explained here and in detail in https://github.com/fancyapps/fancybox/issues/2005#issuecomment-405057281

**Comment by sun4all** [comment]
There are some things I do not understand fully - yet, but that's maybe because of my English or my Math. (or both) I think that someone from the w3c panicted, finding out that systems exist within the order of the order of w3c data-collections, that - so to say - produce values with "missing units". 

For a test I changed my css-stylesheet now, the svg stroke-width on my website from 1.6 to 5% which gives me a similiar visual result. 0 mistakes for my style-sheet now, and 3 warnings because of "vendor-prefixes" (-ms-,-webkit-) from the w3c validation-service (with scan-options: css3 + svg).
Shall I be happy now? 

What I do not understand: The author of the svg-paper shows a drawing with red rectangles, and the third column ist an example section for percentage values, and if you look at the middle one, 3rd column, in the source code, he uses <rect x="0" y="750" width="400" height="200" stroke-width="31.62"/> - that is the result of a sqrt function. "In particular, note that the stroke-width in the middle rectangle is set to 1% of the sqrt((actual-width)**2 + (actual-height)**2) / sqrt(2), which in this case is .01*sqrt(4000*4000+2000*2000)/sqrt(2), or 31.62" - Again, no unit added to this value.
I figured - until now, that a unitless svg value will be treated like a percentage-value or a relative or a proportional value of whatever, or is kind of a shorthand notation: I'm 32, instead of saying I'm 32 years old. 

One thing, I think, I do understand about SVG: I do see unitless values as a BASIS of such a system, it is the nature of such a system, to be able to use plain values that express proportions or relations - without having to use any units. Any inital value for such a (per se) unitless-system, should be for example 1, not 1px, not 1em, not 1%, in order to explain the idea of vector-grafics in general, that is: device and screen-resolution-independent descriptions for drawings/images. If the w3c rethinks such a concept, I do not care. Designing websites since 2002, I do not care anymore, if the w3c crew writes one more draft about whatever; they do/did not "solve" svg for ALMOST 20 YEARS now. What an authority. 

But, it's really ok for me today to type 5% instead of 1.5, if the world around me is happy about that, and if w3c is happy too, life will be great. 

I'm really interested to understand more about svg, because I love vector drawings. For my personal "fancybox 3" I simply HAD to design my own svg buttons. I'm sure Janis will change his css-code regarding stroke-width, sooner or later, he definitely is a master of css, I learned a lot from the fancybox-css he wrote. 
Best Regards, sun4all

**Comment by fancyapps** [comment]
I'll assume that this is issue of W3C CSS validator:

1) default value of `stroke-width` according to W3C itself is `1` - https://svgwg.org/svg2-draft/painting.html#StrokeWidthProperty 
2) MDN Web Docs are perfectly fine with unitless values - https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes

**Comment by sideshowbarker** [comment]
> > 1. default value of stroke-width according to W3C itself is 1 - https://svgwg.org/svg2-draft/painting.html#StrokeWidthProperty
>
> I’ve raised an issue at https://github.com/w3c/svgwg/issues/529

I also raised PR https://github.com/w3c/svgwg/pull/530 with a patch, which has now been merged into the SVG spec sources as https://github.com/w3c/svgwg/commit/9d7859fb00e73eb7f70be5cca41a3b23f643e1c2 (and will be reflected at https://svgwg.org/svg2-draft/painting.html#StrokeWidthProperty the next time the spec is regenerated from those sources).

**Comment by fancyapps** [comment]
@XhmikosR 

I decided to redesign icons without the stroke :) ( https://github.com/fancyapps/fancybox/commit/0000b52d7a5c62e4954c13e5536ccbb5a3c8f967#diff-bcd677ed310ee5134c7e3b9fb323f178R348 )

@sideshowbarker 

Well, on completely unrelated matters, it seems like you're the right person to ask a couple questions :))

1) Why is not "Focus with focusOption" demo not working as expected (using FF; works fine using Chrome) - https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus ? 

2) It would be awesome if this would be properly resolved - https://bugzilla.mozilla.org/show_bug.cgi?id=748518 - that would help a lot; and this related problem - https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container - prevented moving to flexbox :/
