### ISSUE TITLE
How to hide the tool-bar and navigation buttons?

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2035]
In [this album](https://andrewolff.jalbum.net/FancyBoxWeb2/) you can start/stop a slide show by clicking in the slide image. The click event executes the next code:

    function onSlideClicked() {
    	FancyBoxInstance = $.fancybox.getInstance();
    	FancyBoxInstance.SlideShow.toggle();
    	if (FancyBoxInstance.SlideShow.isActive) { 
    		$('.fancybox-toolbar').hide(); $('.fancybox-navigation').hide() }
    	else {  
   		$('.fancybox-toolbar').show(); $('.fancybox-navigation').show() }
  	return false;	
    }

This code hides the tool-bar and navigation buttons while a slide show is playing.
This code is only executed if you click in the slide image, not if you click the play button in the tool-bar.

However the tool-bar is still visible in the transition phase.

How can I prevent that?

Another question: 

How can I get the same effect if I click the Play button in the tool-bar, so is it possible to execute function  onSlideClicked also if the tool-bar Play button is clicked?

**Comment by fancyapps** [comment]
Hi,

You could add custom click event to that button, but that would not be good solution, because slideshow toggles when user presses spacebar key, too.

There is currently no callback when slideshow starts/stops, but I added right now and it will included in the next update, you can preview it here - https://codepen.io/anon/pen/xJvRZe?editors=1010

**Comment by fancyapps** [comment]
btw, there are built in functions to hide/show/toggle controls, for example:

`$.fancybox.getInstance().hideControls();`

similarly, others are `showControls()` and `toggleControls()`

**Comment by acwolff** [comment]
Thanks for your fast response!

If I change the code into:

    function onSlideClicked() {
    	$.fancybox.getInstance().SlideShow.toggle();
    	$.fancybox.getInstance().toggleControls();
    	return false;	
    }

the tool-bar is still visible in the slide transistion phase and the slide caption is also hidden and that is not what I wanted!

**Comment by fancyapps** [comment]
Yes, it would hide caption, too. If you want to show/hide only some parts of the interface, you can do that by adding/removing according class names from the container, for example:

`$.fancybox.getInstance().$refs.container.removeClass("fancybox-show-infobar fancybox-show-toolbar");`

But I do not know why toolbar is flashing for you, try removing that classname instead of hiding using jQuery.

**Comment by acwolff** [comment]
I tried this:

    function onSlideClicked() {
    	$.fancybox.getInstance().SlideShow.toggle();
	if ( $.fancybox.getInstance().SlideShow.isActive ) {
	  $.fancybox.getInstance().$refs.container.removeClass("fancybox-show-infobar fancybox-show-toolbar");
	} else {
	  $.fancybox.getInstance().$refs.container.addClass("fancybox-show-infobar fancybox-show-toolbar");
    	}
    	return false;	
    }

This hides the controls too, but they are  is still visible in the slide transition phase,  [see here](https://andrewolff.jalbum.net/FancyBoxWeb/).

**Comment by fancyapps** [comment]
I think this is related to the same issue that has been discussed in other issues, e.g., your `onSlideClicked` most likely gets executed multiple times.

Closing this, because all my previously posted snippets work fine, thus giving answer to the original comment.
