### ISSUE TITLE
Stutter Swipe

### ISSUE THREAD

**Issue by abrilli** [fancyapps/fancybox#2047]
There is a stutter when you touch swipe an image in order to move to the next image.  It is not smooth or fluid.
 
Is this intended?  Can this be fixed or is there an adjustment somewhere?
 
I tested on Chrome for Android, Firefox for Android, and Safari for iOS.  All 3 browsers have this same behavior.  (Even on the Demo itself on the homepage of Fancybox 3 this happens.)  Otherwise, the lightbox is Awesome!
 
Thank you so much!

**Comment by fancyapps** [comment]
Hi,

What do you mean by "stutter"? Everything seems to work fine for me. The only thing that comes to my mind is that if you swipe fast enough, then the next image might appear suddenly after being loaded. Is that what you mean?

**Comment by abrilli** [comment]
Hi Jānis,
 
Thank you for replying so quickly.
 
I made a screen recording (GitHub requires the MP4 to be embedded in a zip), please see attached "Screen_Recording.zip".
 
There is a stutter or stickiness that occurs when you go to swipe.  Even if you are very forceful with the swipe, there still is a stutter or hesitation.
 
It would be really, really great if this swiping motion could be more like an actual Mobile App.  (Going through photos, say in a gallery app, just very lightly touching and swiping will move the photo smoothly and onto the next one.)
 
Please let me know if you have any thoughts or know of any ideas on how to make this a bit smoother...
 
Thank You So Much!
 
~
[Screen_Recording.zip](https://github.com/fancyapps/fancybox/files/2334289/Screen_Recording.zip)

**Comment by fancyapps** [comment]
Hi,

Thanks for the video. Since I can not see your finger/cursor, I can not be sure, but I got impression that you did not drag image enough to start slide transition. Could it be the reason? e.g., if you would swipe a bit longer (at least 50px), would it work smoother? I think I could tweak the logic to allow fast, but short swipe if that is the case.

**Comment by abrilli** [comment]
Hi Jānis,
 
(I'm still testing to see if this would be necessary.)
 
Although I have a few commercial licenses I would buy.  Also by the way, it may enhance fancyBox all together now and into the future perhaps.
 
So maybe (if it's not too much work) - perhaps you can set the pixels to a variable that can then be set in the options allowing the "Touch Sensitivity" to be adjusted.  That would be pretty spectacular.
 
I doubt there would be any other lightbox projects out there that would have this level of sophistication, and that in turn would be another plus and positive for fancyBox.
 
Just let me know your thoughts if you don't mind...
 
Thanks so much!

**Comment by fancyapps** [comment]
There have been some improvements in the latest version (v3.4.2), it should feel snappier.

Due to some iOS Safari weirdness (it is a long story), something like "Touch Sensitivity" will be implemented in v4, when all animations that currently are created using CSS transitions will be replaced by custom animation engine.
