### ISSUE TITLE
Use `clickContent` to execute custom code

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2048]
I tried this code with the new release:

     $('[data-fancybox="S"]').fancybox({
    //  clickContent: function(current, event) {
    //	$.fancybox.getInstance().SlideShow.toggle();  
    //    return true;  // false;
      clickContent:  function() {
    	 $.fancybox.getInstance().SlideShow.toggle();  
      },
      onSlideShowChange : function(instance, current, active) {
        if ( active ) {
          instance.next();
        }
     },
      buttons : [ "zoom", "slideShow", "close" ]
   });

But clicking in the image does not start the slide show, also not if I use the outcommented code.
This was working in the previous version.

**Comment by fancyapps** [comment]
Hi,

Actually, `SlideShow.toggle()` works fine, but `clickContent` is executed only once, therefore it cannot be used to execute code on each click. 

It is a long story and is related to updating the cursor, because after each layout/slide update we need to know if click action is zoom or not (therefore - we need to change cursor or not). Since you (if I remember correctly) recently created an issue that `clickContent` gets executed too many times while resizing the window, that is executed only once.

**Comment by acwolff** [comment]
The code above prevents also that the slideshow is started if you click the play button.

However, this code:

    function initFancyBox() {
     $('[data-fancybox="S"]').fancybox({
      clickContent:  function() {
    	 return "next"; 
      },
      buttons : [ "zoom", "close" ]
    });
    }
works pefect, here I can use clickContent multiple times and it works as expected.

So it is impossible the use the clickcontent function if the slideshow is enabled?

**Comment by fancyapps** [comment]
See here - https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L1500 - if that option is method, then it is executed once and is replaces by return value.

In the end you have to choose - either that option as method gets executed 1) multiple times, leading to - #2022 issue or 2) or executed only once, leading to this issue.

I think I am going to delete that piece of code and let it be executed as many times as needed.

**Comment by acwolff** [comment]
Sorry, I still don't understand the clickContent function,

If I open fancyBox and use this code:

     $('[data-fancybox="S"]').fancybox({
      clickContent:  function() {
    	alert("clickContent!");
      },
      onSlideShowChange : function(instance, current, active) {
        if ( active ) {
          instance.next();
        }
     },
      buttons : [ "zoom", "slideShow", "close" ]
    });
I get immediately an alert message "clickContent!" although I did not click in the image.

**Comment by fancyapps** [comment]
Well, what I tried to explain - `updateCursor` method uses that option to determine what cursor to set, e.g., if image is zoomable and (return) value of that option is "zoom", then cursor changes to "zoom-in". This is why you see this option executed without clicking.

**Comment by fancyapps** [comment]
Well, today it occured to me that this issue was non-existent, because `clickContent` could receive up to two arguments - 1) `current` object and 2) click `event`. So, all you had to do is to check if 2nd parameter exists or not. 

```JS
$('[data-fancybox="images"]').fancybox({
  clickContent : function(current, event) {
    if (event) {
      console.info( 'Clicked on the content!' );
    }

    return 'zoom';
  }
});
```
Demo - https://codepen.io/anon/pen/eLBMNo?editors=1010

This would not work in v3.4.0, but will work in the next and was working in the previous versions.

**Comment by acwolff** [comment]
Well in [my jAlbum FancyBox  skin](https://jalbum.net/en/skins/skin/FancyBox) I use the click event in this code:

       function initFancyBox() {
         $('[data-fancybox="S"]').fancybox({
           clickContent:  function() {
         	 return "next"; 
           },
          buttons : [ "zoom", "close" ]
         }); 
        }
to go to the next image.

That works without problems as you can see in [this album](https://www.andrewolff.nl/FotoSerie/OverigeTochten/Winterswijk/).
