### ISSUE TITLE
Margin in full screen mode on mobile

### ISSUE THREAD

**Issue by merravid** [fancyapps/fancybox#2066]
The default margin of [44,0] should not be applied in full screen mode on mobile. 

The source code states that the default margin [44,0] is not applied if the screen width is less than 320px, however it appears to be applied in landscape mode on most modern phones.

**Comment by fancyapps** [comment]
Hi,

It seems that you are using older version, because `margin` option has been removed some time ago and is replaced by combination of CSS margin/padding properties.

Due to incistinecy across browsers, you have to set top/right/left padding for the slide (https://github.com/fancyapps/fancybox/blob/master/src/css/core.css#L156) and bottom margin for content element (https://github.com/fancyapps/fancybox/blob/master/src/css/core.css#L175). It is a bit messy thanks to https://stackoverflow.com/questions/29986977/firefox-ignores-padding-when-using-overflowscroll

**Comment by fancyapps** [comment]
I forgot to add that this spacing already changes for small screen devices - https://github.com/fancyapps/fancybox/blob/master/src/css/core.css#L605

**Comment by merravid** [comment]
Hi,

Do you mean that the margin is now hardcoded at 6px on phones and we need to override those css styles to change this default?

**Comment by fancyapps** [comment]
I do not understand why it should be called "hardcoded", but yes, you can override CSS to your liking. That's what css is meant for.
