### ISSUE TITLE
Media types "video / inline" and gallery mode

### ISSUE THREAD

**Issue by meneldil** [fancyapps/fancybox#2073]
Hi,

I have a problem with the media type "video" or "inline" and the mode "gallery".
When it is activated, the window disappears when displaying.

Here's the problem in action:
Video: https://jsfiddle.net/meneldil/qz2gktm0/
Inline: https://jsfiddle.net/meneldil/sv35noLe/

I wish a gallery with several types of mixed media.
How should I do it ?

**Comment by fancyapps** [comment]
Hi,

So, you want to have a gallery of the same, unique element? But .. that is not how it works, that does not make any sense. The idea of "inline" elements is that you can literally display any dom element in the modal, e.g., the script moves that element in the right place and then puts back in the original place. 

And, if you have a gallery, then next/prev slide is preloaded so that swiping would look nice. And, since you have a gallery of the same element, that element gets moved to the current slide and then is immediately moved to the next slide (because of preloading).

**Comment by meneldil** [comment]
In my case, I use the same "inline" which includes a video.
I just dynamically load the video (using data attribut and video.js).

I want to avoid having an infinity of div "inline" while we can have the same result with only one.

**Comment by fancyapps** [comment]
It would be better to do it the other way - add some custom click event to your links, then get all needed info (video id, src, poster, etc) and start fancybox manually. 

Here is a basic demo of the idea - https://jsfiddle.net/kz6g347v/

```HTML
<a href="javascript:;" class="fancybox-video" data-what="AAA">Item 1</a>
<a href="javascript:;" class="fancybox-video" data-what="BBB">Item 2</a>
<a href="javascript:;" class="fancybox-video" data-what="CCC">Item 3</a>
<a href="javascript:;" class="fancybox-video" data-what="DDD">Item 4</a>

<div id="template">{{WHAT}}</div>
```

```JS
$(document).on('click', '.fancybox-video', function() {
  var $this = $(this);
  var $links = $('.fancybox-video');
  var arr = [];

  $.each($links, function(index, item) {
    var what = $(item).data('what');

    arr.push({
      type : 'html',
      src : $('#template').html().replace("{{WHAT}}", what)
    });
  });

  $.fancybox.open(arr, {}, $links.index($this));
});
```

**Comment by meneldil** [comment]
Thank you, I will look at this and come back to you if I have any other questions. :)

**Comment by meneldil** [comment]
I have evolved your code to be able to mix different types of media.
I share for the fancybox community: https://jsfiddle.net/meneldil/es0j35gL/

Thanks again for your help!
