### ISSUE TITLE
Video poster image missing in a slideshow on a mobile device

### ISSUE THREAD

**Issue by acwolff** [fancyapps/fancybox#2075]
Thanks for your fantastic new version 3.4.2 !
I like the new slideshow progressbar!

I see a small problem with this new version on a mobile device like my iPad:

To see it, open [my video test album](https://andrewolff.jalbum.net/FancyBoxVideoTest/) on a mobile device.  The first 5 thumbnails with a red border are video mp4 files. The last 3 thumbnails with a red border are YouTube or Vimeo videos. The other thumbnails are photos, with one web page.

Click on the first image and next start a slide show. On a PC the videos are starting automatically, but on a mobile iOS device you have to start each video by hand. Strange enough, the first video starts automatically in a slideshow. But if the 2nd video is displayed, you see no video poster image and the play button is not in the center of the black image:

![img_1017_noposter_lr](https://user-images.githubusercontent.com/8150784/45896121-72687e80-bdd3-11e8-8bb6-d0903fab69ba.jpg)

 If you click the video play button, the video plays and the slideshow continues to the 3th video, where it stops again without showing the video poster image. The YouTube and Vimeo videos do show the poster image and do not start automatically on an iPad.

If you click on a video thumbnail on the start page, the poster image is always correctly displayed.
Also on a PC there are no problems: you see in a slideshow always the poster images and the videos do start automatically.

**Comment by fancyapps** [comment]
Hi,

fancybox does not currently have option for custom poster image and there is no `poster `tag in video template. From the docs (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video):

> poster
> A URL for an image to be shown while the video is downloading. If this attribute isn't specified, nothing is displayed until the first frame is available, then the first frame is shown as the poster frame.

So, the browser displays first frame while video loads, if poster is not defined, but iOS Safari simply displays nothing. because video is not starting.

To autoplay the video or not is beyond fancybox ability limits, see this docs for Chrome - https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
and https://webkit.org/blog/6784/new-video-policies-for-ios/ for iOS

I'll think about adding `poster` option so at least something will be displayed instead of blank box.

And thanks for your kind words.

**Comment by acwolff** [comment]
Thanks for your fast response.

Adding a poster option is highly appreciated by me, because my output directory contains already poster images:

<img width="293" alt="posters" src="https://user-images.githubusercontent.com/8150784/45899967-9bdad780-bdde-11e8-9113-adc655bf4236.PNG">
