### ISSUE TITLE
Breaking changes? 3.3 -> 3.4

### ISSUE THREAD

**Issue by KayakinKoder** [fancyapps/fancybox#2086]
Reading the changelog, it seems like there are breaking changes in 3.4 e.g.

`Data attributes data-trigger and data-index are renamed to data-fancybox-trigger and data-fancybox-index to avoid conflicts with Bootstrap`

Does this mean that if we previously used `data-trigger` in our code, it will no longer work/will break our site?

**Comment by fancyapps** [comment]
Fancybox follows custom versioning - GENERATION.MAJOR.MINOR , where 
MAJOR - incompatible API changes
MINOR - new functionality (in a backwards-compatible manner) or backwards-compatible bug fixes

So, the answer to your question - "yes, you are right".

**Comment by KayakinKoder** [comment]
I've never seen this before so I'm not sure, but it would seem then that you should not publish as an npm package. This is confusing, causes live site breakages, and is all around a very poor design decision on the part of your package maintainers.

**Comment by KayakinKoder** [comment]
And in fact npm does clearly state this in the `Semver for Publishers` section here: https://docs.npmjs.com/getting-started/semantic-versioning

I can understand from a marketing perspective wanting this "generational" versioning. A better way to do so is to name each generation textually, not using semver versions. E.g.

FancyBox Generation 2
v5.x.x
v4.x.x
v3.x.x

FancyBox Generation 1
v2.x.x
v1.x.x

**Comment by fancyapps** [comment]
Well, there have been discussions about this topic for years - https://github.com/semver/semver/issues/213 - but without proper solution. And, for example, versioning of jQuery (like many older projects) does not match semver rules, too. Unfortunately, semver does not permit "three-dot strategy" - https://www.ibm.com/developerworks/library/mw-1710-phillips/index.html#1Overviewofathree-dotstrategyoutline - but that would solve all issues. 

The good news is that there will be no api changes in v3, because current roadmap is: 
lite wp plugin -> v4 -> wp plugin pro

I have not yet decided what option to choose for v4, maybe it would be best to simply create a new package (fancybox4) and to start a fresh versioning.

**Comment by KayakinKoder** [comment]
I would definitely recommend moving to the standard. This *almost* broke our live site, luckily one of our devs caught it before we deployed. Immediately after that we had a discussion as to whether we should keep using fancybox or find something else. We really like fancybox and would keep buying licenses into the future....as long as we can be relatively certain our site isn't going to break without our knowledge.

Other than this, fancybox has been excellent, thank you.
