### ISSUE TITLE
option for width when open ajax fancybox

### ISSUE THREAD

**Issue by urkoben** [fancyapps/fancybox#2133]
Is there any option, on fancybox 3, for passing the width (or max-width) of the fancybox when opening an ajax content via javascript? something like:

`$.fancybox.open({src:'path/to/content.html',type:'ajax',opt:{ajax:{css:{width:'500px'}}}})`

Is there any other way for doing it without setting it on the content (`<div style="width:500px"> content </div>`)?

Thanx

**Comment by fancyapps** [comment]
Hi,

Usually, in the modern web, you would not want to set fixed dimensions for any element. You can use CSS `width`, `min-width`, `max-width` properties (and combine with CSS Media Queries, if needed) to bring best user experience for clients using any device. Also, it would probably be better to use class names instead of inline styles.

If you really, really want to set some css using js, then you can use callbacks for that.

**Comment by fancyapps** [comment]
FYI, you can simplify that snippet like this:

`current.$content.css('max-width', '800px');`

**Comment by urkoben** [comment]
Thankx! a lot better!
