### ISSUE TITLE
Hidden html content and toolbar

### ISSUE THREAD

**Issue by armlan** [fancyapps/fancybox#2202]
How do I ...Have a hidden html content, this a construct for two image comparison slider, and want to display the toolbar with the zoom button too. Any idea how to pop up the toolbar for hidden html content, fancybox doesn't show the toolbar as default for hidden htmls?
Showing the two image comparison slider works well so far. But want to zoom into the image(s) closer.
Thanks

**Comment by fancyapps** [comment]
Hi,

You could add `data-toolbar="true" ` attribute to your link and then toolbar would be displayed with default buttons - https://codepen.io/anon/pen/NoEZyv

Or you simply set `toolbar : true` when initializing fancybox - https://codepen.io/anon/pen/zeMVEM

But, you would not be able to display default zoom button, because it will be automatically disabled (because it is supposed to be available for images only), but you can easily create your own button, something like this - 

```JS
$('[data-fancybox]').fancybox({
  toolbar : true,
  smallBtn : false,
  buttons : ['my-zoom', 'fullScreen', 'close'],
  btnTpl : {
    'my-zoom' : '<button class="fancybox-button" title="{{ZOOM}}">+/-</button>'
  }
})
```

Demo - https://codepen.io/anon/pen/zeMVEM?editors=1010

See docs for sample how to make button clickable - http://fancyapps.com/fancybox/3/docs/#faq-3

**Comment by enamul1214** [comment]
Is there any way to show the toolbar for html content. I'm totally stuck. 

`
Fancybox.bind('[data-fancybox="gallerys"]', {
    Toolbar: {
        display: [
        { id: "counter", position: "left" },
        "slideshow",
        "fullscreen",
        "thumbs",
        "close",
        ],
    }
});
`

toolbar not showing

**Comment by fancyapps** [comment]
@enamul1214 For Fancybox v4.0, add `autoEnable:false` option, demo - https://fancyapps.com/playground/24T
