### ISSUE TITLE
Content can not be displayed inside iFrame

### ISSUE THREAD

**Issue by toplisek** [fancyapps/fancybox#2203]
How do I ...
I have tested iFrames and message is the white background and translated: Content cannot be displayed. Please try again.

Is this license issue as all code was double checked.

**Comment by fancyapps** [comment]
Hi,

Most likely you forgot to add `data-type="iframe"` to your link, I can not imagine any other reason. Since you did not provide any useful info (https://stackoverflow.com/help/mcve would be preferred), it is not possible to give a more specific answer.

**Comment by toplisek** [comment]
Thank you. You are right. I have added more information: 
If we use code at the bottom, will this work as a PDF viewer? I have tested but my PDF will not work but the second example will work. Is it some issue to show PDF's?
  EXAMPLE1: <a data-fancybox data-type="iframe" data-src="https://mozilla.github.io/pdf" href="javascript:;">
Sample PDF file
  </a>
EXAMPLE2 (working):
  <a data-fancybox data-type="iframe" data-src="https://mozilla.github.io/pdf.js/web/viewer.html" href="javascript:;">
     Example #3 - Sample PDF file
  </a>

**Comment by fancyapps** [comment]
Hmm, do you understand what is HTML and what is PDF? It is not the same. You need something that converts PDF to HTML so that browser can understand and display that. fancybox (in fact, like any modal-type script) is not parsing PDF file, it is out of the scope of this project, therefore you have to use tools like pdf.js.

**Comment by toplisek** [comment]
Thank you for the information.
