### ISSUE TITLE
Close Button, Click-off Pre/Next doesn't work

### ISSUE THREAD

**Issue by armlan** [fancyapps/fancybox#2208]
Hi there, 
developed a simple site with start.html at the top of subfolders containing more html, js, images, thumbs to load (Firefox 65,x,x).
Also local:
Bootstrap: bootstrap-v3.4.0.min.css, bootstrap-v3.4.0.min.js
JQuery: jquery-v3.3.1.min.js
Fancybox v3.5.6: jquery.fancybox.min.css, jquery.fancybox.min.js

If I load start.html from my local machine (containing start and all subfolders) everything works fine.
If I save all files on another pc/laptop/fileserver, I'm facing issues:
1: Loading time increased from a second (all local) to minutes (loading over LAN)
2: This is worse: The close button, click-off, pre/next arrows don't work anymore. No reaction at all.
Other buttons like zoom, resize, thumbnails work fine.
Any ideas?

**Comment by fancyapps** [comment]
Hi,

It is always best to develop using some sort of webserver. For example, I am using Laravel Homestead https://laravel.com/docs/5.8/homestead to create local development environment.

Since script works fine and you did not provide url to live demo where your issue could be inspected, I can't really do anything here.
