### ISSUE TITLE
Click to label not change input checkbox

### ISSUE THREAD

**Issue by jakubkaderavek** [fancyapps/fancybox#2223]
Hi,

a have form in fancybox checkbox with label:
```
<div style="display: none;">
    <form id="my_form">
        <input name="input_10.1" type="checkbox" value="My value" id="choice_1_10_1">
	<label for="choice_1_10_1" id="label_1_10_1">My label</label>
    </form>
</div>

```
If I have form without fancybox, then everything works right. But in fancybox when I click to label, then no action is done.
My js is:

`   $.fancybox.open($('#my_form').html());`

Thanks for help

**Comment by fancyapps** [comment]
Hi,

Since you are displaying HTML contents of existing DOM element, there are two copies of `id="choice_1_10_1"` elements on the page and clicking the label most likely activates the first one.

So, you either display as inline (https://codepen.io/anon/pen/zbbEzp?editors=1010):

```JS
  $.fancybox.open({
    src : $('#my_form'),
    type: 'inline'
  });
```

or do something differently, for example, store html as string in a variable, use ajax, etc

**Comment by jakubkaderavek** [comment]
@fancyapps thanks a lot
