### ISSUE TITLE
Inside Iframe

### ISSUE THREAD

**Issue by pwpx2** [fancyapps/fancybox#2229]
Does anyone has problems using this inside an iframe? I had problems with lightbox2 and i thought this would work since its updated more..
Any workarounds?

**Comment by fancyapps** [comment]
Hi,

The script works fine inside iframe. If you, however, want to start fancybox into parent frame (from within iframed page), then you have to start fancybox manually using `parent.jQuery.fancybox.open()`

**Comment by pwpx2** [comment]
I dont know how to do that. Be more specific.

**Comment by fancyapps** [comment]
So, the idea is that instead of doing `$(selector).fancybox()`, you add your own click event to your element. And then, inside that click event, you start fancybox in parent frame (using the snippet from previous comment). It could be something like this:

```JS

var $fb_links = $('[data-fancybox="gal-iframe-psa"]');

$fb_links.click(function() {

  if ( window.self !== window.top ) {

    window.parent.jQuery.fancybox.open( $fb_links, {
      // Put your options here
      hash : false
    }, $fb_links.index( this ) );

  } else {
    $.fancybox.open( $fb_links, {}, $fb_links.index( this ) );
  }

  return false;

});
```

btw, I'm curious, why do you need to use iframes?

**Comment by pwpx2** [comment]
Its for a chat i use.
