### ISSUE TITLE
import fancybox.css in js file

### ISSUE THREAD

**Issue by mmehdinasiri** [fancyapps/fancybox#2239]
i'm import fancybox.css in my js file but its error : 
```
Uncaught Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

        padding: 75px max(44px, env(safe-area-inset-right)) max(25px, env(safe-area-inset-bottom)) max(44px, env(safe-area-inset-left));
                     ^
      "env(safe-area-inset-right)" is not a number for `max'
      in /home/edalati/Workspace/solo/src/Solo/wwwroot/leia/node_modules/@fancyapps/fancybox/dist/jquery.fancybox.css (line 485, column 23)
```

**Comment by fancyapps** [comment]
Hi,

1) https://webkit.org/blog/7929/designing-websites-for-iphone-x/

2) Do not parse CSS files

**Comment by 7iomka** [comment]
If I were you, I’d do separate sass files, because the vast majority, like myself, use module imports inside sass files or inside js files that are processed through node-sass or webpack sass-loader.
That is, to make your plugin work specifically, you must now include it as a separate file, which is extremely inconvenient in component-based assemblies, where component dependencies are integral to the place where the component is declared.
I'm at a loss with this issue!
