### ISSUE TITLE
Navigation buttons

### ISSUE THREAD

**Issue by mariobigboy** [fancyapps/fancybox#2240]
The navigation buttons appears at the top edges of the screen, i really try everything but i cant get them down. I have the last version, really need help

**Comment by fancyapps** [comment]
Hi,

Navigation buttons are positioned using CSS, therefore there should be no problem. Since you did not provide a link to live page/demo, I can only give one advice: please, learn to debug HTML/CSS. It is not that hard, press F12 and use  web inspector to see what causes your issue. Maybe you have some weird global CSS rules, maybe you included older CSS version, ... Without seeing your page, I can just guess.
