### ISSUE TITLE
Firefox 66 + Win 10 Fullscreen blank/white space

### ISSUE THREAD

**Issue by janarfrei** [fancyapps/fancybox#2251]
Hi, 
after installing latest firefox 66 / win 10, fancybox v3.5.7 fullscreen shows whitespace bottom of fancybox content.
Problem appears only by clicking fancybox own fullscreen button.
If I'll try to inspect the problem, content shows up.
Pressing F11 dosent make such problem.
![fancybox-ff-fullscreen-whitespace](https://user-images.githubusercontent.com/12752729/56969902-c0fea800-6b6e-11e9-9bd2-254e3563c689.png)

**Comment by fancyapps** [comment]
Hi,

It works fine for me (using latest FF, Win10), so I do not know what to comment. You can easily test this on homepage - https://fancyapps.com/fancybox/3/ - hit "Customize button" and enable `Fullscreen` button.

**Comment by janarfrei** [comment]
Hello,
thank you for your answer. Problem still exists. Here is link. 
https://www.iwsgroup.ee/referentsid/#images-209-1
Maybe you can help figure it out :)

**Comment by fancyapps** [comment]
You have done very nice customization, good job! On the other hand, you have stumbled upon weird FF bug and I could not figure out what is causing that or how to overcome. I suspect this is caused by your custom code for caption or thumbs, because, if you run with default layout (e.g., simply `jQuery('.references .gallery a[data-fancybox]').fancybox({ buttons: [ 'toggle', 'fullScreen', 'close' ]});`), then it works fine.
