### ISSUE TITLE
error using html5 figure and figurecaption with #link to an hidden div 

### ISSUE THREAD

**Issue by hanscees** [fancyapps/fancybox#2257]
**Describe the bug**
when using html5 figure and figurecaption with #link to an hidden div 
fancybox makes the pictures disappear

**To Reproduce**
1. goto https://www.hanscees.com/2019/fbox7.html 
2. Click on 'picture two'
3. click arrow to the right
4. See error (image dissappears)

**Expected behavior**
it should work as with html4 as here:
https://www.hanscees.com/2019/fbox8.html 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fancyapps** [comment]
Hi,

I appreciate your effort trying to describe your issue, but it is actually not related to figure/figurecaption or something like that. The reason is that you have multiple links leading to the same `#info3` element and they all are in the same group (because they all have `data-fancybox="images"`). The script tries to preload prev/next gallery items (for nice swiping), but one element can exist only in one place, therefore you see this outcome. So, remove grouping or use `data-trigger` feature (https://codepen.io/fancyapps/pen/VGoRqO?editors=1010) or wait for next major version where you could choose to clone your DOM element (thus avoiding this issue for good).

**Comment by hanscees** [comment]
Hi,

you have so much more insight into this than I do. When you type " simply"  its not simple to me.
 
I have tried to use trigger here:
https://www.hanscees.com/2019/fbox7-trigger.html

but that undoes the whole point of using #infoN. The point of that is to have control over the slide that appears when I click on aan image with fancybox. I want to be able to control the text around the image to be left or right of the image and so on, plus (and thats crucial) to contain links.

The problem I am trying to overcome most here is to have text with links beside or above the image in the carousel.

And also, why does it work in html4 but not in html5? Mystery to me ..

**Comment by fancyapps** [comment]
> And also, why does it work in html4 but not in html5? Mystery to me ..

I already explained, it is not related to html4/html5, your both demos are completely different. In your first demo, you have multiple links having the same attributes - `data-fancybox="images" href="#info3"`

**Comment by hanscees** [comment]
Fancybox is splendid. But is there a trick  to add links to the caption. That's all Im really missing. An href inside the caption leading to an external url.

I am using this html4 or html5 trickery only to add readable text with links. But by doing so I am ruining the fancybox features.

So if there is a way to add a link to an external url in the caption that would make things a lot more simple. But I am afraid it cant be done?

**Comment by fancyapps** [comment]
Seems like you still do not understand what I am trying to explain. The problem is not in using html4/5 and captions can have any html, it does not matter, you can put links, tables, iframes, ... literally anything. 

The problem is that you have invalid HTML structure and you can`t debug your html code. But it is so easy, just hit F12 and check DOM tree. In your source, you have `<figure><a ...><figcaption>...</figcaption></a></figure>` and that is not correct, therefore browser breaks `<a>` into multiple peaces resulting in duplicates. See http://fancyapps.com/fancybox/3/docs/#faq-2 for demo on how to use custom element as caption.

**Comment by hanscees** [comment]
Hi,
I have corrected my mistakes, excuses.
It now works as can be seen on this page https://www.hanscees.com/2019/fbox7.html 

However. your examples on codepen do not work with a link in the caption, this time I have debugged the code (while not having enough knowledge on javascript obviously):


When duplicating you example here: https://codepen.io/fancyapps/pen/aaerxw  and adding a link to the figcaption, things go wrong (an image is duplicated somehow.)
You can see the result here:  https://www.hanscees.com/2019/fbox11.html

But the same figcaption technique works fine here:
https://www.hanscees.com/2019/fbox7.html
No duplicate figures there in the debugscreen

If you could please help by providing a working example of a caption with a link that would be great. 
Perhaps it would even be better to use figcaption by default, since that is compliant with html5.

**Comment by fancyapps** [comment]
`adding a link to the figcaption, things go wrong (an image is duplicated somehow.)`

The same problem as before - wrong DOM element hierarchy and, if you would have looked more carefully at debug console, you would discover that browser has again created an empty anchor to compensate invalid HTML code. You have nested `<a`> inside another one and to solve this, either use the same html template as before, but update `caption()` method so it finds and returns correct caption source or get rid of parent anchor and use it like this:

https://codepen.io/anon/pen/WBGQaz?editors=1010

**Comment by hanscees** [comment]
you are basically saying:
no fancybox cannot have a link inside a caption, without destroying all usefulness of fancybox.
Pity you cannot give a working example, only critique.

**Comment by hanscees** [comment]
I really had to look twice to get it, but that's a beautiful example of a link in a caption.
Here it is with my pics
https://www.hanscees.com/2019/fbox12.html

If you could add that to your documentation as an example that would really rock. 
Thanks a lot!!
