### ISSUE TITLE
YouTube Videos with autoplay in Inline content restart after close in FireFox

### ISSUE THREAD

**Issue by Brockenstein** [fancyapps/fancybox#2266]
**Describe the bug**
YouTube Videos with autoplay in Inline content restart after close in FireFox

**To Reproduce**
1. Make sure audio is on
2. In Fire Fox go to https://codepen.io/Brockenstein/pen/ZNKXmz
3.  Scroll down to the image
4. Click on the image
5. Close FancyBox and wait one second audio will restart

**Comment by fancyapps** [comment]
Hi,

First, do you really think that it is a good idea to add hidden auto-playing youtube video in the page? Some browsers will prevent auto-play and it will be fine (https://developers.google.com/web/updates/2017/09/autoplay-policy-changes), but others might start your video and the user would not have a clue where does that sound come from.

The idea of "inline content" is that script literally moves your DOM element into the modal and then puts back after closing. This is perfect for forms or similar stuff, because all the changes user makes stay there untouched. In your case, you have embedded youtube video and, obviously, video keeps playing after closing, because the script is not touching your content (well, it pauses HTML5 videos, but it was implemented, because it was easy to do :))

So, you have two solutions:

1) display a clone instead of real DOM element - https://codepen.io/anon/pen/yWbRVQ
2) restart iframes after closing - https://codepen.io/anon/pen/mYmzLM
