### ISSUE TITLE
Esc key doesn't work when YouTube video is interacted with

### ISSUE THREAD

**Issue by davidtmiller** [fancyapps/fancybox#2273]
**Describe the bug**
When opening a YouTube video, the escape key works as intended, but if you interact with the player the escape key no longer works.

**To Reproduce**
1. Go to http://fancyapps.com/fancybox/3/
2. Click on the 'Default settings of YouTube video' demo
3. Use the esc key on the keyboard
4. The window closes
5. Click on the demo again
6. This time, interact with the player (Pause/Play, Volume, Go to a different point in video, etc.)
7. Use the esc key on the keyboard after interacting with the player
8. The window does not close

**Expected behavior**
It would be expected that the window would close when the esc key is pressed, even after the YouTube video has been interacted with

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [Version 74.0.3729.169 (Official Build) (64-bit)]

Tested in Firefox and Safari as well, same issue.

Hopefully this report helps! Thanks!

**Comment by fancyapps** [comment]
Hi,

I understand why you call this an issue, but this is how HTML/browsers work. You see, YouTube player is inside iframe and, if iframed page gets focus, it also captures key events and, due to browser security policies, you can not detect them from parent page (and you can not bind them directly due to CORS).
