### ISSUE TITLE
Ajax Content not centered in IE

### ISSUE THREAD

**Issue by marcohanke** [fancyapps/fancybox#2279]
I use Fancybox to load ajax content like this:
```<a data-fancybox data-type="ajax" href="__my__url__"><i class="fa fa-2x fa-envelope mr-2"></i></a>```
Its working fine on Chrome, Firefox and Safari. With IE 9 and Up i get a black screen but no content. If i scroll down, i see the content so it is not really centered and i cant find a solution.

**Comment by fancyapps** [comment]
Hi,

1) IE9&10 are not supported.
2) Out of curiosity I checked how it looks on IE9 (using IE11 to emulate) and everything kinda works and centering definitely works fine, as expected, because fancybox uses v3 inline-block trick (see https://codepen.io/edge0703/pen/iHJuA) for centering and it should work on any browser.

So, please, show your page or demo where your issue could be inspected.

![32vr0r](https://user-images.githubusercontent.com/1055589/59092341-fd65b680-8919-11e9-9ca3-d5d491261c39.jpg)

**Comment by marcohanke** [comment]
I've the same Problem in IE11 with ajax and also with an inline modal ;-(
http://alex.36pixel.de

**Comment by fancyapps** [comment]
This is caused by the combination of weird HTML structure of your content and CSS. As I explained, the script uses inline-block trick for vertical centering, because it is reliable and has best browser support. 

However, there is one minor issue with that trick - if content exceeds parent element width, then browser might decide to put content below pseudo element. Like in your case (e.g., your element has 100% width and has padding on both sides). Possible solutions for you: wrap your element having class name `.container` into another wrapping container; change `width:100%` to something like `width: calc(100% - 88px)`

**Comment by marcohanke** [comment]
Thanks for this Solution!
