### ISSUE TITLE
Absolutely positioned element prevents fancyBox animationEffect zoom from working

### ISSUE THREAD

**Issue by EugeneDae** [fancyapps/fancybox#2281]
Absolutely positioned element within the [data-fancybox] element prevents `animationEffect: zoom` from working. FancyBox versions prior to 3.4.2 didn't exhibit this behavior.

Reduced test case on CodePen with FancyBox 3.5.7:
https://codepen.io/EugeneDae/pen/ZNgPwb

Comment out `<div class="overlay"></div>` to get `animationEffect: zoom` working again.

Possible duplicate issue: https://github.com/fancyapps/fancybox/issues/2174

**Comment by fancyapps** [comment]
Hi,

The problem is that script uses nifty trick - `document.elementFromPoint()` - to check if thumbnails is really visible. But by creating absolute element over the image, you are "effectively breaking" this feature :)

You can fix that by setting `pointer-events: none;` to your element - https://codepen.io/anon/pen/ewOmOZ

**Comment by EugeneDae** [comment]
@fancyapps Thank you so much!

**Comment by EddieOne** [comment]
![image](https://user-images.githubusercontent.com/1835156/84728832-6cbfae80-af4f-11ea-95ee-38d508252413.png)

I have a similar problem after updating to the lastest 2.x version. Though, in my case I am using fancybox buttons. Do you know how to solve it?
