### ISSUE TITLE
link to another page from within opened fancybox slide 

### ISSUE THREAD

**Issue by bibliofille** [fancyapps/fancybox#2285]
**Describe the bug**
I have a button within the opened fancybox slide that should link to another page within the site, but it is currently not working. 

**To Reproduce**
1. Go to [https://phillipsmedisize.moveodev.com/what-we-do/](https://phillipsmedisize.moveodev.com/what-we-do/)
2. Click on the large blue content area with icons. 
3. Scroll down to the blue button that says "more about front-end innovation."
4. See error: This button should take you to a different page, however it does not, even though the url is correct. 

**Expected behavior**
The button close the slider and take you to a different page within the site. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fancyapps** [comment]
Hi,

So, you have this HTML:

```HTML
<div class="slider-slide" data-fancybox="slides" style="display: none;" id="hidden-content">
  <div class="slider__overlay-inner">
    [removed]

    <div class="slider__button-container">
      <a href="https://phillipsmedisize.moveodev.com/what-we-do/front-end-innovation/" class="button-primary is-centered slider__button">More about front-end innovation </a>
    </div>
  </div>
</div>
```

You see, you have added `data-fancybox` attribute to `.slider-slide` element therefore it automatically acts as a trigger element, e.g., clicking that element will start fancybox. And therefore your link will not work as expected, because parent element is already working as a big button.

Also, you have this JS:

```JS
jQuery(document).ready(function() {
    jQuery(".slider-slide").fancybox({
       infobar: true,
       backFocus : true,
    });
});
```

So, to make it work, remove that JS, remove `data-fancybox="slides"` from `.slider-slide` elements.


Next, you have this HTML structure:

```HTML
<div class="service__item">
  <a data-fancybox="" data-src="#hidden-content" href="javascript:;">
    <div class="serviceline__icon-wrapper">

      <img src="https://phillipsmedisize.moveodev.com/webfoo/wp-content/uploads/FrontEnd-Innovation-white.svg" class="serviceline__icon">

    </div>	<!-- end serviceline__icon-wrapper -->

    <div>
      <h3 class="serviceline__headline">Front End Innovation </h3>
      <p class="serviceline__text">A strong device strategy is needed</p>

    </div>	
  </a>
</div>
```

I am surprised that this even works, because it is semantically incorrect to place block elements (`<div>`) inside inline elements (`<a>`). The solution is simple - there is no need for `<a>` elements at all, add `data-fancybox` and `data-src` attributes to parent element, e.g., 

```HTML
<div class="service__item" data-fancybox="" data-src="#hidden-content">
    <div class="serviceline__icon-wrapper">
        [..]
    </div>	
</div>
```
