### ISSUE TITLE
clickOutside not working on Safari iOS

### ISSUE THREAD

**Issue by CjBrown74** [fancyapps/fancybox#2286]
I'm trying to close a fancybox modal when you click on the outside (background). I'm using the clickOutside method which works fine on all browsers and mobiles, apart from iOS Safari.

`$('[data-fancybox]').fancybox({
        	toolbar: false,
            clickOutside: "close",
        });`

 - Device: iPhone
 - OS: 11, 12
 - Browser: Safari

**Comment by fancyapps** [comment]
Hi,

First, I believe that you are looking for `clickSlide` option, because each slide covers whole window unless you have resized using custom CSS (therefore you can not click on background element by default).

Secondly, for mobile devices, there is a separate option `mobile` that overrides other options, for example, 

```JS
$('[data-fancybox]').fancybox({ 
  toolbar: false, 
  clickSlide: "close", 
  mobile : {
    clickSlide: "close", 
  }
});
```
