### ISSUE TITLE
Fixed iframe width not working as expected

### ISSUE THREAD

**Issue by hirschferkel** [fancyapps/fancybox#2290]
Hi,

I'm trying to set a fixed width for an iframe, but unfortunately if the viewport gets smaller than the fixed width, the iframe jumps to the bottom. Any idea how to create an iframe with fixed height and width which will stay in the center of the screen or on the very left or top of the viewport, when it's dimensions are too big?

Best, hirschferkel

[Codepen example of iframe with fixed width](https://codepen.io/Hirschferkel/pen/PrGWVX)

**Comment by fancyapps** [comment]
Hi,

Explanation - fancybox avoids using JS for content positioning and uses CSS instead. `inline-block` (or `ghost element`) trick is used for vertical positioning (you can google for that if you want to know more) - it is very reliable trick and has good browser support, but the only drawback is that when element width exceeds parent element width, browser can decide to put element in new line, below pseudo element. 

Obviously, the simplest solution would be to avoid setting `min-width` and to use `max-width` CSS property instead of hard coding element width - https://codepen.io/anon/pen/vqXxeP

But, if you really wish to use fixed dimensions, you can use other CSS alignment techniques, for example - https://codepen.io/anon/pen/ZdpexJ

**Comment by hirschferkel** [comment]
O.k. I see. Thanks for your help.

**Comment by hirschferkel** [comment]
In this case I need a fixed iframe contianer. But your example does not work quite right.
If you get smaller in height, the fancybox disappears at the top?

>> https://codepen.io/anon/pen/ZdpexJ

**Comment by fancyapps** [comment]
But that is how CSS works. If you do not like that, then, please, you are welcome to contribute to CSS specs and  to patch all browsers. JS can be the last rescue, but that is not great option either. FYI, none of the modals on Google products (gmail, youtube) work perfectly, too. And that is the one of the richest companies on the world...

**Comment by hirschferkel** [comment]
Doesn't deal with Google and that's not how CSS works. 
Should be possible to set position of fancybox content to absolute and top to 0, no?

Actually fancybox computes a margin to the bottom, that's why it dissapears. 

`margin-bottom: 44px;`

There is just a wrong CSS issue, that's all.

**Comment by fancyapps** [comment]
There is no issue at all, everything works perfectly fine by default. If you apply your modifications, then, obviously, it is your responsibility to make it work and not to break something.
