### ISSUE TITLE
Fancybox 3 working on desktop, not on android

### ISSUE THREAD

**Issue by sipi41** [fancyapps/fancybox#2298]
sorry for interrupting you, just wanted to tell you that I think I found a bug.  I created a set of images like this: 

`<a data-fancybox="gallery" href="/pictures/commercial-painting/commercial-paint-1-md.jpg">
  <div class="GalleryImgDiv" style="background-image:url('/pictures/commercial-painting/commercial-paint-1-sm.jpg');"></div></a>
<a data-fancybox="gallery" href="/pictures/misc/misc-1-md.jpg"><div class="GalleryImgDiv" style="background-image:url('/pictures/misc/misc-1-sm.jpg');"></div>
</a>
...
`
This seems to work as expected on desktop (specifically chrome and mozilla) but when I did a test on android, it show the box with the image but when touching (or clicking) the fancybox never opens...  I did try on android 9 chrome and firefox, same result.

any idea why is this happening? as this is a mobile, I'm not able to see the console for errors or anything... completely blind here.  Thanks for your help.

**Comment by fancyapps** [comment]
Hi,

The script works fine, as you can see on homepage or any other demo.

You did not provide a link to your page/demo, therefore it is not possible to properly inspect your issue. But, by looking at your piece of code, I can see that you have block elements (`<div>`) inside inline elements (`<a>`). That is generally not a good idea, because 1) it is semantically incorrect; 2) browsers can decide to fix your code and that could lead to unexpected results (e.g., `<a><div></div></a>` might become `<a></a><div></div><a></a>`). 

You can easily simplify your structure by replacing
`<a data-fancybox="gallery" href="image.jpg"><div class="GalleryImgDiv" style=""></div></a>`
with
`<div data-fancybox="gallery" data-src="image.jpg" class="GalleryImgDiv" style=""></div>`

**Comment by sipi41** [comment]
Hi! I did what you told me but still the same thing, on mobile when I press over the image, fancybox simply does not fire. :-(

**Comment by fancyapps** [comment]
Well, then the next guess is that you might have some JS error on your page and that can prevent further execution of the code.

I really want to help, but I have to see your page. If you do not want to share URL publicly, you can DM on Twitter or send email to info at fancyapps dot com.

**Comment by sipi41** [comment]
Curiously there are no errors, the problem was caused by a swipe module used by bootstrap and jquery, when I removed the plug-in, it works.  **Thank you for your patience.**

**Comment by acwolff** [comment]
@sipi41 why don't you tell us exactly which module was giving problems, so that other users can prevent the same problem?

@fancyapps is it possible to use on a index / thumbnails page the same swipe module as is used in the lightbox? Is there documentation how to use your swipe module?
