### ISSUE TITLE
How to auto-resize iframe to device width and height?

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2339]
Based on your demos I am able to open youtube videos and external URLs by using the iframe setup you recommend... however, the iframe does not expand to the edges (both full height and full width)... how can I force it to do so?

Thanks and keep making MAGIC!!!

**Comment by fancyapps** [comment]
Hi,

Without any details, I guess you refer to free space around iframe. That space is allocated for close button and navigation arrows (and space at the bottom is for, well, aesthetic reasons). That space is created the same way as for any other content type - using padding for `slide` element. So, to make iframes 100% width/height, you have to remove that padding:

```CSS
.fancybox-slide--iframe {
  padding: 0;
}
```
Then you have to do something about close button, for example:

```CSS
.fancybox-slide--iframe .fancybox-close-small {
  top: 0;
  right: 0;
  background: #000;
}
```
and you would also have to disable iframe preloading, example:

```
$('[data-fancybox="test"]').fancybox({
	toolbar  : false,
	smallBtn : true,
	iframe : {
		preload : false
	}
})
```

Demo - https://jsfiddle.net/vs34765u/

But, it would not work for youtube/vimeo video links, because the script calculates iframe height based on available width and aspect ratio (to avoid black bars), and there is currently no option to disable that. But you could link to youtube videos directly (like `https://www.youtube.com/embed/KDPja9lNeEc`), then it would work the same.
