### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by mhlozek** [fancyapps/fancybox#2377]
I just want to ask if this project is still alive.
Last commit is from March, there are lot of pull requests...

**Comment by fancyapps** [comment]
Hi,

This project is very alive and has been since year 2008. As you can see (https://github.com/fancyapps/fancybox/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature+request%22), there are a lot of feature requests, but some of them (for example, to drop jQuery) take long time to fulfill. It is very challenging to work simultaneously on two large code bases (e.g., current version and upcoming version that will be complete rewrite and redesign) and to provide proper support at the same time. There are no big companies/sponsors behind this project and it is not profitable enough to hire several people. I do my best to provide support (not only here https://github.com/fancyapps/fancybox/issues?q=is%3Aissue+is%3Aclosed but also on SO https://stackoverflow.com/users/486595/janis and privately), but development continuous inside private GitHub repository, therefore you can not see all the activity.

Anyway, thanks for asking!
