### ISSUE TITLE
Can fancybox play .mov fiiles on iOS devices inside an iFrame?

### ISSUE THREAD

**Issue by inglesuniversal** [fancyapps/fancybox#2384]
I own a Mac and I tried loading a video through an iFrame, but all I get is a white square (empty icon)?

Can Videos (.mov files) be forced to play only on iOS devices at least?

Thanks

**Comment by fancyapps** [comment]
Hi,

1) Did you try to resize iframe content to some reasonable dimensions using CSS or JS? The script resizes iframe to match content size by default, but maybe your page has no dimensions at all, it is not possible to tell without seeing your page. 

2) fancybox can display any HTML code, the rest is up to you and to the browser. The script is not downloading files and is not playing videos like some desktop software (e.g., like vlc). iOS has supported HTML5 videos since beginning (and therefore pushed flashplayer out of business).
