### ISSUE TITLE
Autoplay youtube video

### ISSUE THREAD

**Issue by Egretta** [fancyapps/fancybox#2399]
my code:

`<a data-fancybox href="https://www.youtube.com/watch?v=EdAUz9emkv0&amp;rel=0&amp;autoplay=1">Open</a>
`

but it is not working, i still need to click play button. is it possible?

**Comment by fancyapps** [comment]
Hi,

This has been already discussed multiple times, but the reason is that Chrome (and other browsers followed that, too) decided to change their autoplay policy, you can read about that here - 
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

That means that you either have to mute your videos (add `&mute=1`) or to hope that "Media Engagement Index" will be above threshold.
