### ISSUE TITLE
translateZ elements are in front of fancybox on safari 

### ISSUE THREAD

**Issue by wouters** [fancyapps/fancybox#2412]
All elements on the page that have transform: translateZ higher then 1 stay on top and are thus in front of fancybox. Not a real bug, but a pain in the ass. I only noticed this on Safari. It's quite difficult to remove all translateZ from all elements. So I solved this by putting the fancybox even further in front with this code:

```
	.fancybox-container{
		transform: translateZ(99px);
		}
```

i took me quite a while to figure out so i thought i would leave it here in case anyone else is running into this.

**Comment by fancyapps** [comment]
Hi,

Well, the problem is that any CSS rule on your page can affect fancybox. For example, I have seen crazy layouts having absolute positioned body element, etc, but it is just not possible to predict and cover all possible scenarios. Shadow DOM could solve this issue, but the browser support is not perfect.

Your fix looks perfectly fine to me.
