### ISSUE TITLE
Not Working With ReactJS 

### ISSUE THREAD

**Issue by KamranMaqbool** [fancyapps/fancybox#2427]
i'am using this package with reactJS but not Working 
i have to install this package with npm and also install jQuery with npm 
and also include fancybox.css but working 
any solution please ?

**Comment by mjcampagna** [comment]
I haven’t attempted to use Fancybox in React, but I work in React all day long, and have (sadly) had to deal with jQuery in React. 

My findings have been that:

It’s better to load jQuery as a static resource in the head of your base document, rather than via npm. 

That done, you can either do the same with Fancybox, or load Fancybox dynamically in your React component, not as an import, but via script loader. e.g. if not loaded, load the script; if loaded and script is in memory, do not load again. 

For the CSS, put it in your global style sheet. If you’re using styled components, or some form of style scoping, that’s fine. You should still have a global style sheet at your base and can either link Fancybox CSS as a static resource, or CSS import it into that style sheet.

**Comment by fancyapps** [comment]
Hi,

I am closing this, because:

1) fancybox from v1 to v3 are just jQuery plugins, you use them just like any other jQuery plugin. I am sure you can find an info about how to use jQuery plugins with your setup.

2) I believe there is already a feature request to add support for React
