### ISSUE TITLE
Loading of larger files is not stable

### ISSUE THREAD

**Issue by BugFixNo1** [fancyapps/fancybox#2441]
**Describe the bug**
larger files (e.g. gallery with 1MB files) cannot be loaded. There is a white border or an error message is displayed (file cannot be displayed)

also the preload: true with data-width=" " data-height=" " does not work correctly. the faster you try to jump through the gallery, the more often the error occurs

**To Reproduce**
simply load 5MB files in a gallery

**Expected behavior**
show loading progress until file is loaded completely (a real time loading bar would be great, but is not mantadory of course)

thx

**Comment by fancyapps** [comment]
Hi,

Sorry, but browsers can easily be crushed by loading large images and adding CSS animations. You could try to disable all CSS transitions, but that would only help for desktop browsers, mobile browsers would most likely crash just because of the file size. The solution would be to resize images to reasonable sizes or to split image into multiple tiles and to use smth like leafletjs to display them.

**Comment by BugFixNo1** [comment]
Hi, unfortunately i can not agree. Other lightbox scripts do what i discribed. Try the original from Lokesh Dhakar for instance. It's old and dusty thing but loading large files works perfect.

**Comment by fancyapps** [comment]
FYI, I was curious how upcoming fancybox v4 handles large image sizes, so I created test gallery with heavy images (~4,5MB) - and it performs very well, both on desktop and mobile. Check it out - https://fancyapps.com/next/ - look for "Test heavy images".

**Comment by BugFixNo1** [comment]
Great works perfect! Thank you i'm excited to use it! Over all really a excellent job!  When can I expect a publication of v4?

**Comment by fancyapps** [comment]
Oh, it is hard to give an estimate. For example, I planned this morning to do smth else :) But it is coming soon.
