### ISSUE TITLE
How to close FancyBox by "Back" button?

### ISSUE THREAD

**Issue by Nes313** [fancyapps/fancybox#2450]
Trying to close FancyBox by pressing "back" button on browser, but browser linked me to prev link

How to close fancybox with link to current page?

**Comment by fancyapps** [comment]
Hi,

fancybox is already working as you described and you can see this on the homepage as well.

Implementing "close by pressing back button" is very tricky, because you do not have access to actual "back" button and can not control the action when user clicks it. That is why the script ("hash" plugin) creates new entry (on opening) in the browser history and, when user navigates, url hash changes, the script detects that and then open/closes fancybox accordingly.
