### ISSUE TITLE
Different rendering quality on Chrome and Firefox when image zoomed

### ISSUE THREAD

**Issue by asavchuk** [fancyapps/fancybox#2472]
**Describe the bug**
Different rendering quality on Chrome and Firefox when image zoomed.
In Chrome zoomed image looks blurred.

**To Reproduce**
1. Open the same index file on Crome and Firefox. [fancybox-bug](https://github.com/asavchuk/fancybox-bug)
2. Click on thumbnail image
3. Click on image to zoom it in both browsers
4. Look the diffrence in image rendering quality (Firefox quality is perfect but not Chrome).

**Expected behavior**
Rendering quality must be the same in Chrome and Firefox when image zoomed.

**Desktop (please complete the following information):**
 - OS: win
 - Browser: chrome anf firefox
 - Version: the latest

**Comment by fancyapps** [comment]
Hi,

Closing this, because I do not think there is anything I could possibly do to improve image rendering.  I can just suggest to try next major version of fancybox after it will be released. The script just creates html markup, the actual rendering depends on the browser and capabilities of your device.
