### ISSUE TITLE
Is there an alternative to loading web pages in an iframe?

### ISSUE THREAD

**Issue by Lavadus** [fancyapps/fancybox#2494]
I've got links in an svg that trigger hyperlinks to web pages that appear in an overlay, like [this](https://codepen.io/Cabajero21/pen/BajMpPp). This is to provide document citations for research projects.
Several sites that I need to cite will not load in iframes. Instead, a popup appears explaining that they don't allow that.
Is there a way around this? 
Thanks in advance for any suggestions.

**Comment by fancyapps** [comment]
Hi,

The only reliable solution is to use some proxy script on your server. E.g., instead of linking directly to external page, you link to your script (written in PHP, for example) where you read (for example, using `file_get_contents()` or CURL) and return page contents  depending from some parameter.
