### ISSUE TITLE
Compilation Error with SASS

### ISSUE THREAD

**Issue by baszero** [fancyapps/fancybox#2520]
**Describe the bug**
I compile the jquery.fancybox.min.css with `npm node-sass` and get this error:

`env(safe-area-inset-right) is not a number for 'max'`

**To Reproduce**
1. download the current min css version (3.5.7) from https://fancyapps.com/fancybox/3/
2. try to compile just the min.css with node-sass (v4.14.1) on macOS

**Expected behavior**
every CSS should be able to get compiled by any SASS compiler

**Desktop (please complete the following information):**
 - OS: 10.14.6

**Screenshot**
![image](https://user-images.githubusercontent.com/596855/96417827-27a7d380-11f2-11eb-9f2a-4f66716d30df.png)

**Comment by buccia** [comment]
this could be the solution:
https://stackoverflow.com/questions/47439446/using-css-level-4-max-function-in-sass-for-iphone-x-safe-area-styling/47439447#47439447

**Comment by fabiocaccamo** [comment]
@buccia thank you for linking the solution.
@baszero is it planned to fix this issue soon?

**Comment by fancyapps** [comment]
Hi,

First, this issue is caused by the fact that you try to transpile CSS file ... into CSS. 

Secondly, there are no plans to do major changes in current version, but the next generation of Fancybox does not have this issue, because it already uses SCSS (like so https://github.com/fancyapps/ui/blob/main/src/Fancybox/scss/base.scss), see https://github.com/fancyapps/fancybox/issues/1346#issuecomment-853844350
