### ISSUE TITLE
History plugin

### ISSUE THREAD

**Issue by Veron161** [fancyapps/fancybox#35]
I wonder if is possible to include "histroy plugin" to fancybox2.

it would be very nice feature

**Comment by fancyapps** [comment]
Hash module will be included in fancyBox v3.1, you can already preview it here - http://fancyapps.com/fancybox/3/#quick-view-1

**Comment by pekka** [comment]
> Hash module is included in fancyBox v3, you can preview it here -

Nice!

Is there a ready-made way to make this work with "real", non hash-bang URLs, history.js style, so there's a chance to provide server-side Metadata (description, title, Facebook OpenGraph stuff...) when an image is linked directly?

**Comment by fancyapps** [comment]
With real links? Sorry, I do not see how this could be implemented so that it would work for everyone. 

Anyway, you can easily implement your logic (with or without library like hash.js), e.g, on page start check for some condition and trigger click event for the relevant link. And, if you wish, you can use callbacks to change URL when navigating the gallery.
