### ISSUE TITLE
Fancybox Leaves Page When Opening iFrame URL First Time

### ISSUE THREAD

**Issue by ryanjbonnell** [fancyapps/fancybox#441]
I believe I've found a bug in Fancybox v2.1.3 when opening external "iframe type" content for the very first time.

Consider the following example:

```
<a href="http://example.com/">Open in Fancybox</a>

<script>
    $('a').fancybox({
        type: 'iframe',
        autoSize: false,
        href: $(this).attr('href'),
        width: 990,
        height: 600
    });
</script>
```

http://jsfiddle.net/ryanjbonnell/jfqWJ/show/light/

When you first click on the link, Fancybox starts to open and then the browser _leaves the page you're viewing_ and immediately takes you to the URL it attempted to load.

It feels like frame-busting is in effect... however, if you revisit the jsFiddle a subsequent time and click on the same link, Fancybox loads the content without any issues.

**The problem seems to be the first time it tries loading the content.**

This behavior doesn't happen with other jQuery Lightbox plugins I tested, so I don't believe it's a problem with the third-party site.

Tested using **Fancybox 2.1.3** with **jQuery 1.8.2** using **Chrome 22.0** on **Mac OS X 10.8.2**

**Comment by tridoan** [comment]
Sorry to bring this back from 6 years ago, but we're noticing this same behavior on version 2.1.5 on a legacy site. Obviously, upgrading would make sense, but that's not something we're able to safely do at the moment. Was there any resolution to this issue or at least it ended up being a confirmed bug?

**Comment by fancyapps** [comment]
@tridoan Sorry, but nothing has changed since then, this issue is NOT related to fancybox. 

Since that particular page (generously provided by @ryanjbonnell ) has not changed, you can easily check that by yourself - 

1) start fresh Chrome's Incognito mode 

2) open this demo - http://jsfiddle.net/23pjqh4t/

3) As you can see, that demo contains only one (and eampty) element - `<iframe src="http://www.wildflowernutrition.com/restaurant-single-item.php?rid=1570"/>

4) Now, check the console, you will see something like this:

    `Unsafe JavaScript attempt to initiate navigation for frame with origin 'http://jsfiddle.net' from frame with URL 'http://www.wildflowernutrition.com/restaurant-single-item.php?rid=1570'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.`

    That means - iframed page attempts to change location of the parent page.

5) Run the demo again, iframe contents loads fine and no new error message.
