### ISSUE TITLE
Touch detection yields false positives on some desktop platforms

### ISSUE THREAD

**Issue by DanielStolt** [fancyapps/fancyBox#893]
The following is used to detect a "touch" device:

`isTouch = document.createTouch !== undefined,`

In the desktop version of Chrome (although this may not be limited to Chrome) this evaluates to true just as long as the machine happens to have a touch screen. This results in a number of problems for Fancybox:
- Double scroll bars are rendered for a scrollable iframe
- The automatic resizing of the Fancybox based on window resize is inactivated

I think this code should be improved to not only detect touch capabilities but also whether it's a mobile device.

**Comment by gedeh** [comment]
Hi we also having big issue with implementation of touch support detection in 2.1.5. Also note that document.createTouch() API is deprecated (https://developer.mozilla.org/en-US/docs/Web/API/Document/createTouch). 

We use fancy-box with ASP.NET web forms, the touch detection makes DOM tree of fancybox-inner element rendered outside of the form tag despite already use parent: 'form:first' option. This causes view state of the elements not recognized after a post-back

**Comment by SalahAdDin** [comment]
I think that we should fork this repository and do anyone new with all PR.

**Comment by naniwa23** [comment]
This also disables outer click to close. Instead of closing controls' visibility is toggled.

I know, that it is difficult to distinguish between mobile device with touch and desktop devices with touch. Actually there is no elegant way to do this.
Anyway, for some projects I need to distinguish and I detect, if the device has a mouse and it was moved - but take care, at a touch event `mousemove` is also triggered.

For fancybox3 we could use something like this:

```javascript
var is_touch_event = false;

function hasMouse() {
    if(is_touch_event === false) {
        $.fancybox.isTouch = false;
        document.body.removeEventListener('mousemove', hasMouse);
    }
}

document.body.addEventListener('mousemove', hasMouse);

document.body.addEventListener('touchstart', function ()  {
    is_touch_event = true;
});
```

**Comment by fancyapps** [comment]
v3 now combines simple UA sniffing to detect mobile devices.
